\documentclass[a4paper, 9pt]{scrartcl}
\usepackage[ngerman]{babel}

% -----------------------------------------------------------------------
<<init, echo = FALSE>>=
pacman::p_load(tidyverse, simstudy, knitr, xtable, kableExtra, readxl, plyr,
               gridExtra, broom, effectsize, gtsummary, glmmTMB, performance,
               janitor, pander, lme4, corpcor, fs)
##
options(show.signif.stars = FALSE)
options(scipen = 0, digits = 7)
##set.seed(20240701) ## savety seed 
##
opts_chunk$set(fig.width=7, fig.height=7, fig.path='img/',
               echo=FALSE, warning=FALSE, message=FALSE, 
               cache.path='cache/', fig.pos='H')
## get the paths
if(str_detect(path_home(), "^C:")){
  exam_path <- file.path(path_home(), "Documents/GitHub/exam")
} else {
  exam_path <- file.path(path_home(), "work/GitHub/exam")  
}
init_path <- file.path(exam_path, "init")
question_path <- file.path(exam_path, "question")
img_path <- file.path(question_path, "img")

## get the question files
questions_vec <- list.files(question_path,
                            full.names = TRUE, pattern = "Rnw")

text_questions_vec <- str_subset(questions_vec, "mc|math|tier|stat_test", negate = TRUE)
mc_questions_vec <- str_subset(questions_vec, "mc-", negate = FALSE)
math_questions_vec <- str_subset(questions_vec, "math-", negate = FALSE)
tier_questions_vec <- str_subset(questions_vec, "tier-", negate = FALSE)
stat_test_questions_vec <- str_subset(questions_vec, "stat_test-", negate = FALSE)
desc_stat_questions_vec <- str_subset(questions_vec, "desc_stat-", negate = FALSE)
ttest_questions_vec <- str_subset(questions_vec, "/ttest-", negate = FALSE)
anova_questions_vec <- str_subset(questions_vec, "/anova-", negate = FALSE)
chisquare_questions_vec <- str_subset(questions_vec, "/chisquare-", negate = FALSE)
linreg_questions_vec <- str_subset(questions_vec, "/linreg-", negate = FALSE)
## nonpar_questions_vec <- str_subset(questions_vec, "/nonpar-", negate = FALSE)
multcomp_questions_vec <- str_subset(questions_vec, "/multcomp-", negate = FALSE)
experimental_questions_vec <- str_subset(questions_vec, "/experiment-", negate = FALSE)
forsch_lern_questions_vec <- str_subset(questions_vec, "/forsch-", negate = FALSE)
program_questions_vec <- str_subset(questions_vec, "/program-", negate = FALSE)

## get the points per question
points_tbl <- read_excel(file.path(exam_path, "questions_points.xlsx"))

## dummy select function
wanted_questions <- c(text_questions_vec, math_questions_vec) %>% sample(7)

## get the points done
ques_points_tbl <- points_tbl %>% 
  filter(file_name %in% basename(wanted_questions))
points_vec <- ques_points_tbl %>% pull(points) 

textpoints <- sum(points_vec) 
overallpoints <- textpoints + 20

## Build up the grade table
pre_grade_tbl <- unique(cut(overallpoints:(overallpoints/2), 10)) %>% 
  as_tibble() %>% 
  separate(value, into = c("low", "high"), sep = ",") %>% 
  mutate(low = str_replace_all(low, "\\(", ""),
         high = str_replace_all(high, "\\]", "")) %>% 
  mutate_if(is.character, as.numeric) %>% 
  mutate(low = round(low/0.5) * 0.5 + 0.5,
         high = round(high/0.5) * 0.5)

## be sure the lowest grade at half points
pre_grade_tbl$low[10] <- overallpoints/2

#if((overallpoints/2)%%1 != 0) {
pre_grade_tbl$low <- str_pad(pre_grade_tbl$low, 3, "right", "0") %>% 
  str_replace_all("0$", ".0")
pre_grade_tbl$high <- str_pad(pre_grade_tbl$high, 3, "right", "0") %>% 
  str_replace_all("0$", ".0")
#}

## final grade table
grade_tbl <- pre_grade_tbl %>% 
  mutate(Punkte = str_c(low, " - ", high),
         Note = c("1.0", "1.3", "1.7", "2.0", "2.3", 
                 "2.7", "3.0", "3.3", "3.7", "4.0")) %>% 
  select(Punkte, Note)

## random ID
exam_id <- sample(c("\\square", "\\blacksquare"), 20, replace = TRUE) |> 
  str_c(collapse = "\\!")

## global parameters
naming_global <- c(rep(c("Jessica", "Paula", "Tina", "Nilufar"), each = 2), "Yuki",
                   rep(c("Mark", "Jonas", "Alex", "Steffen"), each = 2), "Yuki") |> 
  set_names(c(rep("sie", 9), rep("er", 9))) 

plant <- c("Maiss", "Erbsen", "Kartoffeln", "Lauch", 
           "Erdbeeren", "Brokkoli", "Spargel") %>% 
  sample(1) |> 
  set_names("pflanze")
animal <- c("Puten", "Schweinen", "Fleischrindern", 
            "Lamas", "Hühnern", "Zandern", "Milchvieh") |> 
  sample(1) |> 
  set_names("tier")
obser <- c(plant, animal) |> sample(1)

par_lst <- lst(year = "2024",
               naming = naming_global,
               obser = c(plant, animal) |> sample(1))

## Monster des Alltags
attr_lst <- lst(Alex = lst(flaw = "die Gefälligkeit", sweet = "Gummibärchen", animal = "die Katze", sport = "zu Laufen",
                         hobby = "Starcraft", music = "Abba", film = "Alien"),
                Jessica = lst(flaw = "der Mangel", sweet = "Schokobons", animal = "der Hund", sport = "Rad zu fahren",
                         hobby = "Warhammer", music = "David Bowie", film = "Herr der Ringe"),
                Jonas = lst(flaw = "die Erschöpfung", sweet = "Snickers", animal = "das Meerschweinchen", sport = "zu Schwimmen",
                         hobby = "Stricken", music = "Iron Maiden", film = "Mission Impossible"),
                Mark = lst(flaw = "die Unsicherheit", sweet = "Marzipankugeln", animal = "der Hamster", sport = "zu Reiten",
                         hobby = "Geocaching", music = "Andrea Berg", film = "Columbo"),
                Nilufar = lst(flaw = "die Erwartung", sweet = "Takis Blue Heat", animal = "das Huhn", sport = "zu Kicken",
                         hobby = "Blasmusik", music = "Deichkind", film = "Star Trek"),
                Paula = lst(flaw = "der Perfektionismus", sweet = "Smarties", animal = "die Ratte", sport = "zu Fechten",
                         hobby = "Harry Potter", music = "White Lies", film = "Jagd auf roter Oktober"),
                Steffen = lst(flaw = "die Romantik", sweet = "Oreos", animal = "der Leguan", sport = "zu Ringen",
                         hobby = "Klemmbausteine", music = "Taylor Swift", film = "Harry Potter"),
                Tina = lst(flaw = "die Wut", sweet = "Katjes", animal = "die Spinne", sport = "zu Boxen",
                         hobby = "Astronomie", music = "Tocotronic", film = "Indiana Jones"),
                Yuki = lst(flaw = "die Faulheit", sweet = "Reese's Peanut Butter Cups", animal = "das Minischwein", sport = "zu Boldern",
                         hobby = "Orchideen", music = "London Grammar", film = "Matrix"))


sentence_func <- \(name, pronom, attr_vec){
  sentence_lst <- lst(flaw = c(str_c(name, " und ", attr_vec$flaw ,", eine unendliche Geschichte mit kniffeligen Wendungen."),
                               str_c("Eine echte Herausforderung für ", pronom[5] ," war schon immer ", attr_vec$flaw ," gewesen. Ein leidiges Lied."),
                               str_c("Wenn ", attr_vec$flaw ," nicht wäre, ja dann wäre wohl vieles möglich für ", name ,"! Aber so..")) |> sample(1),
                      sweet_music = c(str_c(name, " schmeißt noch eine Handvoll ", attr_vec$sweet ," in ", pronom[3] ," Rachen. Im Hintergrund klirrt leise der Spiegel zum Sound von ", attr_vec$music ,"."),
                                      str_c("'Hm...', ", attr_vec$sweet ," und ", attr_vec$music ,". Das ist und bleibt die beste Kombination zum Nachdenken für ", name ,"."),
                                      str_c("Aus den Boxen wummert ", attr_vec$music ," und ", pronom[7] ," Mund ist verklebt von ", attr_vec$sweet ,". 'Herrlich', denkt ", name ,".")) |> sample(1),
                      animal_music = c(str_c(name, " streichelt liebevoll ", attr_vec$animal ,". Der Kopf ist in ", pronom[1] ," Schloß vergraben um den Klang von ", attr_vec$music ," zu dämpfen."),
                                       str_c("Wenn ", attr_vec$music ," ertönt, dann sucht ", attr_vec$animal ," schleunigst Schutz unter dem Sofa. ", name ," schüttelt den Kopf."),
                                       str_c(name, " nickt im Takt von ", attr_vec$music ," und bemerkt dabei gar nicht was ", attr_vec$animal ," schon wieder anstellt.")) |> sample(1),
                      sport = c(str_c(name, " will später nochmal raus um ", attr_vec$sport ,". Druck ablassen, dass muss ", names(name) ," auch."),
                                str_c("Um ", attr_vec$sport ," geht ", name ," dann später nochmal raus. Echte Entspannung."),
                                str_c("Einfach mal raus um ", attr_vec$sport ,". Ohne Ziel und Uhr. Das ist was für ", name ,".")) |> sample(1),
                      hobby = c(str_c(name, " liebt ", attr_vec$hobby ,". Darin kann ", names(name) ," sich wirklich verlieren und immer wieder neu begeistern."),
                                str_c("", attr_vec$hobby ,". Ein wunderbares Hobby um sich drin zu verlieren und Abstand zu bekommen. ", name ," denkt gerne über ", attr_vec$hobby ," nach."),
                                str_c("Am Ende dann doch besser ", attr_vec$hobby ,". Wunderbar. Eine echte Ablenkung für ", name ,".")) |> sample(1),
                      sweet_film = c(str_c("Hm, lecker ", attr_vec$sweet ," und dazu dann im Hintergrund ", attr_vec$film ," laufen lassen."),
                                     str_c("Auf seinem Second Screen läuft ", attr_vec$film ," und ", name ," schaufelt ", attr_vec$sweet ,". Nicht effizient, aber gut."),
                                     str_c("Schon dutzende Male gesehen: ", attr_vec$film ,". Aber immer noch großartig zusammen mit ", attr_vec$sweet ,".")) |> sample(1),
                      animal_film = c(str_c("Das Verrückte ist, dass ", attr_vec$animal ," ", attr_vec$film ," wirklich liebt. Das ist ", name ," sehr recht, denn ", names(name) ," braucht Entspannung."),
                                      str_c("Wenn ", attr_vec$film ," läuft, dann ist ", attr_vec$animal ," nicht mehr da. Aber jetzt braucht ", names(name) ," mal Entspannung!"),
                                      str_c("Irgendwie komisch, wenn ", names(name) ," ", attr_vec$film ," anmacht, dann ist ", attr_vec$animal ," eigentlich sofort vor dem Bildschirm und starrt hinein.")) |> sample(1))
  return(sentence_lst)
}

@ 
% -----------------------------------------------------------------------
\input{\Sexpr{init_path}}
% -----------------------------------------------------------------------
\begin{document}
\date{Wintersemester 2024/25 
\vfill
\begin{center}
\includegraphics[width = 1.9cm]{avatare/Alex}\hspace{-8mm}
\includegraphics[width = 1.9cm]{avatare/Jessica}\hspace{-8mm}
\includegraphics[width = 1.9cm]{avatare/Jonas}\hspace{-8mm}
\includegraphics[width = 1.9cm]{avatare/Mark}\hspace{-8mm}
\includegraphics[width = 1.9cm]{avatare/Nilufar}\hspace{-8mm}
\includegraphics[width = 1.9cm]{avatare/Paula}\hspace{-8mm}
\includegraphics[width = 1.9cm]{avatare/Steffen}\hspace{-8mm}
\includegraphics[width = 1.9cm]{avatare/Tina}\hspace{-8mm}
\includegraphics[width = 1.9cm]{avatare/Yuki}\\
\small
\vspace{1.5Ex}
\textit{"`The test of a student is not how much he knows,\\ but how much he wants to know."'\\ --- Alice W. Rollins}
\end{center}}
% -----------------------------------------------------------------------
\maketitle
\fancypagestyle{empty}{
  \fancyfoot[L]{\tiny $\Sexpr{exam_id}$}
}
\thispagestyle{empty}
\clearpage
% -----------------------------------------------------------------------

\begin{graybox}{Erlaubte Hilfsmittel}
  \vspace{1Ex}
  \begin{itemize}
  \item Normaler Taschenrechner ohne Möglichkeit der Kommunikation mit anderen
    Geräten! Ausdrücklich kein Handy!
  \item Eine DIN A4-Seite als beidseitig, selbstgeschriebene,
    handschriftliche Formelsammlung. Keine digitalen Ausdrucke! 
  \item \textbf{\textcolor{red}{Die Verwendung eines roten Farbstiftes ist nicht gestattet! Korrekturfarbe!}}
  \item \textit{You can answer the questions in English without any consequences.}  
  \end{itemize}
\end{graybox}
\vfill

\begin{graybox}{Endnote}
  \vspace{1Ex}
  \begin{itemize}
  \item[] \rule[0ex]{3em}{.4pt}\, von 20\, Punkten sind aus den Multiple
    Choice Aufgaben erreicht.
  \item[] \rule[0ex]{3em}{.4pt}\, von \Sexpr{textpoints} Punkten sind aus den Rechen- und
    Textaufgaben erreicht. 
  \item[] \rule[0ex]{3em}{.4pt}\, von \Sexpr{overallpoints} Punkten in Summe.
  \item[] Es wird folgender Notenschlüssel angewendet.   
  \end{itemize}
  \vspace{1ex}
\begin{center}
  \begin{tabular}[c]{cc}
    \toprule
    \textbf{Punkte}	&	\textbf{Note}	\\
    \midrule
    \Sexpr{grade_tbl$Punkte[1]}	&	1,0	\\
    \Sexpr{grade_tbl$Punkte[2]}	&	1,3	\\
    \Sexpr{grade_tbl$Punkte[3]}	&	1,7	\\
    \Sexpr{grade_tbl$Punkte[4]}	&	2,0	\\
    \Sexpr{grade_tbl$Punkte[5]}	&	2,3	\\
    \Sexpr{grade_tbl$Punkte[6]}	&	2,7	\\
    \Sexpr{grade_tbl$Punkte[7]}	&	3,0	\\
    \Sexpr{grade_tbl$Punkte[8]}	&	3,3	\\
    \Sexpr{grade_tbl$Punkte[9]}	&	3,7	\\
    \Sexpr{grade_tbl$Punkte[10]}	&	4,0	\\
    \bottomrule
  \end{tabular}
\end{center}
  \vspace{1ex}
\begin{itemize}
\item[] Es ergibt sich eine Endnote von \rule[0ex]{4em}{.4pt}.
\end{itemize}
  \vspace{1Ex}
\end{graybox}

% -----------------------------------------------------------------------
\newpage
% -----------------------------------------------------------------------

\begin{graybox}{Multiple Choice Aufgaben}
  \begin{itemize}
  \item Pro Multipe Choice Frage ist \emph{genau} eine Antwort richtig.
  \item \textbf{Übertragen Sie Ihre Kreuze in die Tabelle auf
      dieser Seite.}
  \end{itemize}

\begin{center}
  \large
  \begin{tabular}{|l|c|c|c|c|c?c|}
    \hline
    & \textbf{A} & \textbf{B} & \textbf{C} & \textbf{D} & \textbf{E} & $\boldsymbol{\checkmark}$\strut\\
    \hline
    \textbf{Aufgabe 1} &   &   &   &   &   & \strut\\
    \hline
    \textbf{Aufgabe 2} &   &   &   &   &   & \strut\\
    \hline
    \textbf{Aufgabe 3} &   &   &   &   &   & \strut\\
    \hline
    \textbf{Aufgabe 4} &   &   &   &   &   & \strut\\
    \hline
    \textbf{Aufgabe 5} &   &   &   &   &   & \strut\\
    \hline
    \textbf{Aufgabe 6} &   &   &   &   &   & \strut\\
    \hline
    \textbf{Aufgabe 7} &   &   &   &   &   & \strut\\
    \hline
    \textbf{Aufgabe 8} &   &   &   &   &   & \strut\\
    \hline
    \textbf{Aufgabe 9} &   &   &   &   &   & \strut\\
    \hline
    \textbf{Aufgabe 10} &   &   &   &   &   & \strut\\
    \hline
  \end{tabular}
\end{center}

\begin{itemize}
\item Es sind \rule[0ex]{2em}{.4pt}\, von 20 Punkten erreicht worden.
\end{itemize}
\end{graybox}

\vfill

\begin{graybox}{Rechen- und Textaufgaben}
  \begin{center}
    \large
    \begin{tabular}{|l|c|c|c|c|c|c|c|}
      \hline
      \textbf{Aufgabe} & \textbf{11} & \textbf{12} & \textbf{13} & \textbf{14} & \textbf{15} & \textbf{16} & \textbf{17} \strut\\
      \hline
      \textbf{Punkte} & 
      \hspace{1Ex}\Large\textcolor{gray!70}{\Sexpr{points_vec[1]}}\hspace{1Ex}  & 
      \hspace{1Ex}\Large\textcolor{gray!70}{\Sexpr{points_vec[2]}}\hspace{1Ex}  & 
      \hspace{1Ex}\Large\textcolor{gray!70}{\Sexpr{points_vec[3]}}\hspace{1Ex}  & 
      \hspace{1Ex}\Large\textcolor{gray!70}{\Sexpr{points_vec[4]}}\hspace{1Ex}  & 
      \hspace{1Ex}\Large\textcolor{gray!70}{\Sexpr{points_vec[5]}}\hspace{1Ex}  & 
      \hspace{1Ex}\Large\textcolor{gray!70}{\Sexpr{points_vec[6]}}\hspace{1Ex}  & 
      \hspace{1Ex}\Large\textcolor{gray!70}{\Sexpr{points_vec[7]}}\hspace{1Ex} \strut\\
      \hline
  \end{tabular}
\end{center}
\begin{itemize}
\item Es sind \rule[0ex]{2em}{.4pt}\, von \Sexpr{textpoints} Punkten erreicht worden.
\end{itemize}
\end{graybox}

% -----------------------------------------------------------------------
\clearpage
% -----------------------------------------------------------------------
\begin{graybox}{Multiple Choice Aufgaben}
Die Multiple Choice Aufgaben \textcolor{red}{unterliegen dem Zufall}. Die Reihenfolge der Antworten ist zufällig. Die Fragen und Antworten sind semantisch zufällig und haben somit \textcolor{red}{verschiedene Textvarianten}. Insbesondere die reinen Textaufgaben haben verschiedene Textvarianten. Die Semeantik mag sich unterscheiden, die Inhalte sind aber gleich.
\end{graybox}
\section*{ANOVA}
\Sexpr{knit_child(mc_questions_vec[1])} 
\Sexpr{knit_child(mc_questions_vec[2])} 
\Sexpr{knit_child(mc_questions_vec[3])} 
\Sexpr{knit_child(mc_questions_vec[4])} 
\Sexpr{knit_child(mc_questions_vec[5])} 
\section*{Deskriptive Statistik \& Explorative Datenanalyse}
\Sexpr{knit_child(mc_questions_vec[6])} 
\Sexpr{knit_child(mc_questions_vec[7])} 
\Sexpr{knit_child(mc_questions_vec[8])}
\Sexpr{knit_child(mc_questions_vec[9])} 
\Sexpr{knit_child(mc_questions_vec[10])}
\Sexpr{knit_child(mc_questions_vec[11])}
\Sexpr{knit_child(mc_questions_vec[12])}
\Sexpr{knit_child(mc_questions_vec[13])} 
\Sexpr{knit_child(mc_questions_vec[14])} 
\section*{Lineare Regression \& Korrelation}
\Sexpr{knit_child(mc_questions_vec[15])}
\Sexpr{knit_child(mc_questions_vec[16])}
\Sexpr{knit_child(mc_questions_vec[17])}
\Sexpr{knit_child(mc_questions_vec[18])}
\Sexpr{knit_child(mc_questions_vec[19])}
\Sexpr{knit_child(mc_questions_vec[20])}
\Sexpr{knit_child(mc_questions_vec[21])}
\section*{Vermischte Themen}  
\Sexpr{knit_child(mc_questions_vec[22])}
\Sexpr{knit_child(mc_questions_vec[23])}
\Sexpr{knit_child(mc_questions_vec[24])}
\Sexpr{knit_child(mc_questions_vec[25])}
\Sexpr{knit_child(mc_questions_vec[26])}
\Sexpr{knit_child(mc_questions_vec[27])}
\Sexpr{knit_child(mc_questions_vec[28])}
\section*{Multiple Gruppenvergleiche}    
\Sexpr{knit_child(mc_questions_vec[29])}
\Sexpr{knit_child(mc_questions_vec[30])}
\Sexpr{knit_child(mc_questions_vec[31])}
\Sexpr{knit_child(mc_questions_vec[32])}
\Sexpr{knit_child(mc_questions_vec[33])}
\section*{Statistische Testtheorie}  
\Sexpr{knit_child(mc_questions_vec[34])}
\Sexpr{knit_child(mc_questions_vec[35])}
\Sexpr{knit_child(mc_questions_vec[36])}
\Sexpr{knit_child(mc_questions_vec[37])}
\Sexpr{knit_child(mc_questions_vec[38])}
\Sexpr{knit_child(mc_questions_vec[39])}
\Sexpr{knit_child(mc_questions_vec[40])}
\Sexpr{knit_child(mc_questions_vec[41])}
\Sexpr{knit_child(mc_questions_vec[42])}
\Sexpr{knit_child(mc_questions_vec[43])}
\Sexpr{knit_child(mc_questions_vec[44])}
\Sexpr{knit_child(mc_questions_vec[45])}
\Sexpr{knit_child(mc_questions_vec[46])}
\section*{Statistische Tests für Gruppenvergleiche} 
\Sexpr{knit_child(mc_questions_vec[47])}
\Sexpr{knit_child(mc_questions_vec[48])}
\Sexpr{knit_child(mc_questions_vec[49])}
\Sexpr{knit_child(mc_questions_vec[50])}
    
% -----------------------------------------------------------------------
\clearpage
% -----------------------------------------------------------------------
\part{Deskriptive Statistik \& Explorative Datenanalyse}
% -----------------------------------------------------------------------
\Sexpr{knit_child(desc_stat_questions_vec[1])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(desc_stat_questions_vec[2])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(desc_stat_questions_vec[3])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(desc_stat_questions_vec[4])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(desc_stat_questions_vec[5])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(desc_stat_questions_vec[6])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(desc_stat_questions_vec[7])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(desc_stat_questions_vec[8])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(desc_stat_questions_vec[9])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(desc_stat_questions_vec[10])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(desc_stat_questions_vec[11])} 
\clearpage
% -----------------------------------------------------------------------
\part{Statistisches Testen \& statistische Testtheorie}
% -----------------------------------------------------------------------  
\Sexpr{knit_child(stat_test_questions_vec[1])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(stat_test_questions_vec[2])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(stat_test_questions_vec[3])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(stat_test_questions_vec[4])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(stat_test_questions_vec[5])} 
\clearpage
% -----------------------------------------------------------------------
\part{Der Student t-Test, Welch t-Test \& gepaarter t-Test}
% -----------------------------------------------------------------------
\Sexpr{knit_child(ttest_questions_vec[1])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(ttest_questions_vec[2])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(ttest_questions_vec[3])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(ttest_questions_vec[4])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(ttest_questions_vec[5])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(ttest_questions_vec[6])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(ttest_questions_vec[7])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(ttest_questions_vec[8])} 
\clearpage
% -----------------------------------------------------------------------
\part{Die einfaktorielle \& zweifaktorielle ANOVA}
% -----------------------------------------------------------------------
\Sexpr{knit_child(anova_questions_vec[1])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(anova_questions_vec[2])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(anova_questions_vec[3])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(anova_questions_vec[4])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(anova_questions_vec[5])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(anova_questions_vec[6])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(anova_questions_vec[7])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(anova_questions_vec[8])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(anova_questions_vec[9])} 
\clearpage
% -----------------------------------------------------------------------
\part{Multiple Gruppenvergleiche}
% ----------------------------------------------------------------------- 
\Sexpr{knit_child(multcomp_questions_vec[1])} 
\clearpage
% ----------------------------------------------------------------------- 
\Sexpr{knit_child(multcomp_questions_vec[2])} 
\clearpage
% ----------------------------------------------------------------------- 
\Sexpr{knit_child(multcomp_questions_vec[3])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(multcomp_questions_vec[4])} 
\clearpage
% -----------------------------------------------------------------------
\part{Der Chi-Quadrat-Test \& Der diagnostische Test}
% -----------------------------------------------------------------------
\Sexpr{knit_child(chisquare_questions_vec[1])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(chisquare_questions_vec[2])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(chisquare_questions_vec[3])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(chisquare_questions_vec[4])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(chisquare_questions_vec[5])} 
\clearpage
% -----------------------------------------------------------------------
\part{Lineare Regression \& Korrelation}
% -----------------------------------------------------------------------
\Sexpr{knit_child(linreg_questions_vec[1])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(linreg_questions_vec[2])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(linreg_questions_vec[3])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(linreg_questions_vec[4])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(linreg_questions_vec[5])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(linreg_questions_vec[6])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(linreg_questions_vec[7])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(linreg_questions_vec[8])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(linreg_questions_vec[9])} 
\clearpage
% -----------------------------------------------------------------------
\part{Experimentelles Design}
% -----------------------------------------------------------------------
\Sexpr{knit_child(experimental_questions_vec[1])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(experimental_questions_vec[2])} 
\clearpage
% -----------------------------------------------------------------------
\part{Programmieren in R}
% -----------------------------------------------------------------------
\Sexpr{knit_child(program_questions_vec[1])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(program_questions_vec[2])} 
\clearpage
% -----------------------------------------------------------------------
\part{Forschendes Lernen}

Das forschende Lernen basiert zum einen auf den folgenden wissenschaftlichen Veröffentlichungen. Für die Prüfung wird die vertiefende Kenntnis der folgenden Veröffentlichungen vorausgesetzt.\\

\textit{In der Prüfung erhalten Sie einen Auszug der wissenschaftlichen Veröffentlichung. Für die Einarbeitung in die Veröffentlichung ist in der Prüfung \underline{ausdrücklich} keine Zeit vorgesehen.}

\begin{itemize}[noitemsep]
\item Sánchez, M., Velásquez, Y., González, M., \& Cuevas, J. (2022). Hoverfly pollination enhances yield and fruit quality in mango under protected cultivation. Scientia Horticulturae, 304, 111320. [\href{https://www.sciencedirect.com/science/article/pii/S0304423822004411}{Link}]
% \item Salinas, I., Hueso, J. J., Força Baroni, D., \& Cuevas, J. (2023). Plant growth, yield, and fruit size improvements in ‘Alicia’papaya multiplied by grafting. Plants, 12(5), 1189. [\href{https://www.mdpi.com/2223-7747/12/5/1189}{Link}]
\item Petersen, F., Demann, J., Restemeyer, D., Olfs, H. W., Westendarp, H., Appenroth, K. J., \& Ulbrich, A. (2022). Influence of light intensity and spectrum on duckweed growth and proteins in a small-scale, re-circulating indoor vertical farm. Plants, 11(8), 1010. [\href{https://www.mdpi.com/2223-7747/11/8/1010}{Link}]
\item Selle, P. H., Cadogan, D. J., Li, X., \& Bryden, W. L. (2010). Implications of sorghum in broiler chicken nutrition. Animal Feed Science and Technology, 156(3-4), 57-74. [\href{https://www.sciencedirect.com/science/article/pii/S0377840110000209}{Link}]
\item Wu, G., Knabe, D. A., \& Kim, S. W. (2004). Arginine nutrition in neonatal pigs. The Journal of Nutrition, 134(10), 2783S-2790S. [\href{https://www.sciencedirect.com/science/article/pii/S0022316623031279}{Link}]
\end{itemize}

Das forschende Lernen basiert zum anderen auf den folgenden wissenschaftlichen Datensätzen und deren vertiefende Analyse werden als bekannt vorausgesetzt. Die Teilaufgaben der Aufgaben stellen nur eine zufällige Auswahl an möglichen Fragen dar. Die Datensätze werden über ILIAS bereitgestellt.\\

\textit{In der Prüfung erhalten Sie \underline{keinen Auszug} aus den wissenschaftlichen Daten. Die Datensätze werden als \underline{bekannt} in der Prüfung vorgesetzt. Sie haben sich vorab Notizen und Anmerkungen gemacht.}

\begin{itemize}[noitemsep]
\item bar
\end{itemize}

\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(forsch_lern_questions_vec[1])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(forsch_lern_questions_vec[2])} 
\clearpage
% -----------------------------------------------------------------------
\part{Mathematik}
% -----------------------------------------------------------------------  
\Sexpr{knit_child(math_questions_vec[1])} 
\clearpage
% ----------------------------------------------------------------------- 
\Sexpr{knit_child(math_questions_vec[2])} 
\clearpage
% ----------------------------------------------------------------------- 
\Sexpr{knit_child(math_questions_vec[3])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(math_questions_vec[4])} 
\clearpage
% ----------------------------------------------------------------------- 
\Sexpr{knit_child(math_questions_vec[5])} 
\clearpage
% ----------------------------------------------------------------------- 
\Sexpr{knit_child(math_questions_vec[6])} 
\clearpage
% ----------------------------------------------------------------------- 
\Sexpr{knit_child(math_questions_vec[7])} 
\clearpage
% ----------------------------------------------------------------------- 
\Sexpr{knit_child(math_questions_vec[8])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(math_questions_vec[9])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(math_questions_vec[10])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(math_questions_vec[11])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(math_questions_vec[12])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(math_questions_vec[13])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(math_questions_vec[14])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(math_questions_vec[15])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(math_questions_vec[16])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(math_questions_vec[17])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(math_questions_vec[18])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(math_questions_vec[19])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(math_questions_vec[20])} 
\clearpage
% -----------------------------------------------------------------------
\Sexpr{knit_child(math_questions_vec[21])} 
\clearpage
% -----------------------------------------------------------------------
\part{Angewandte Nutztier- und Pflanzenwissenschaften (M.Sc.)}
% -----------------------------------------------------------------------  
\Sexpr{knit_child(tier_questions_vec[1])}
\Sexpr{knit_child(tier_questions_vec[2])}
\Sexpr{knit_child(tier_questions_vec[3])} 
\end{document}
% -----------------------------------------------------------------------


  