\section{Aufgabe \hfill (9 Punkte)}

%% --------------------------------------------------------------------
\hfill\href{https://youtu.be/3DfWs9NNrCk}{\includegraphics[width =
  2cm]{img/youtube}}\\[1Ex]
%% --------------------------------------------------------------------


<<>>=
time_vec <- sample(c("Monat", "Jahr", "halben Jahr"), 1)
words <- c("(Unbekannte) Wahrheit", "H$_0$ wahr", "H$_0$ falsch",
           "H$_0$ abgelehnt", "H$_0$ beibehalten", "Testentscheidung",
           "$\\alpha$-Fehler", "$\\beta$-Fehler", "Richtige Entscheidung",
           "5\\%", "20\\%") %>% sample(4)
@ 

\begin{enumerate}
\item Tragen Sie folgende Fachbegriffe zur statistischen Testtheorie korrekt eine passende Kreuztabelle ein! \textbf{(3 Punkte)}
  \begin{itemize}
  \item \Sexpr{words[1]}
  \item \Sexpr{words[2]}
  \item \Sexpr{words[3]}
  \item \Sexpr{words[4]}
  \end{itemize}
\item Erg{\"a}nzen Sie die Kreuztabelle um vier weitere, passende Fachbegriffe zur statistischen Testtheorie! \textbf{(2 Punkte)}
\item In der Analogie des Feuermelders, wie lautet der $\alpha$-Fehler? \textbf{(1 Punkt)}
\item In der Analogie des Feuermelders, wie lautet der $\beta$-Fehler? \textbf{(1 Punkt)}
\item Wenn der Feuermelder einmal pro Tag messen w{\"u}rde, wie oft w{\"u}rde der
  Feuermelder mit einem $\alpha$ von 5\% in einem \Sexpr{time_vec} Alarm schlagen?
  Begr{\"u}nden Sie Ihre Antwort! \textbf{(2 Punkte)}
\end{enumerate}




