\section{Aufgabe \hfill (6 Punkte)}

\begin{enumerate}
\item Erkl{\"a}ren Sie den Zusammenhang zwischen Stichprobe und Grundgesamtheit
  an einem Schaubild! \textbf{(3 Punkte)}
\item Was ist der Unterschied zwischen $\mu$ und $\sigma$ und $\bar{y}$ und
  $s$ im Kontext der Stichprobe und Grundgesamtheit? \textbf{(2 Punkte)}
\item Warum m{\"u}ssen wir {\"u}berhaupt zwischen einer Stichprobe und einer
  Grundgesamtheit unterscheiden? \textbf{(1 Punkt)}
\end{enumerate}