\section{Aufgabe \hfill (8 Punkte)}

In einer ANOVA wird die F Statistik nach der Formel $F_{calc} = \cfrac{MS_{treatment}}{MS_{error}}$ berechnet. In einem t-test berechnen wir die T Statistik nach der Formel $T_{calc} = \cfrac{\bar{y}_1 - \bar{y}_2}{s_p \cdot \sqrt{2/n_g}}$.

\begin{enumerate}
\item Erklären Sie den konzeptionellen Zusammenhang zwischen der $F_{calc}$ Statistik und $T_{calc}$ Statistik! \textbf{(2 Punkte)}
\item Visualisieren Sie eine nicht signifikante $F_{calc}$ Statistik sowie eine signifikante $F_{calc}$ Statistik! Beschriften Sie die Abbildung! \textbf{(2 Punkte)}
\item Erklären Sie an der Formel des F-Tests sowie an der Abbildung warum das Minimum der F-Statistik 0 ist! \textbf{(2 Punkte)}
\item Wenn die  F-Statistik 0 ist, spricht dies eher für oder gegen die Nullhypothese? Begünden Sie Ihre Antwort! \textbf{(2 Punkte)}
\end{enumerate}


