\section{Aufgabe \hfill (12 Punkte)}

\textit{Geben Sie grundsätzlich Formeln und Rechenweg zur Lösung der Teilaufgaben mit an!} \\[1Ex]
 
<<>>=
name <- par_lst$naming |> sample(1)
avatar_file <- list.files(file.path(exam_path, "avatare"), full.names = TRUE)|> 
  str_subset(name)
jahr <- par_lst$year
obser <- par_lst$obser |> sample(1) |> magrittr::extract2(1) |> sample(1)
avatar1file <- str_c("\\includegraphics[width = 1.3cm]{", avatar_file, "}")
@
 
%% --------------------------------------------------------------------
\begin{minipage}[t]{0.5\textwidth}
\Sexpr{avatar1file}
\end{minipage}
\begin{minipage}[t]{0.5\textwidth}
\hfill
\href{https://youtu.be/8Pb2sKUIMyk}{\includegraphics[width = 2cm]{img/youtube}}\\[1Ex]
\end{minipage}
\vspace{1ex}
%% --------------------------------------------------------------------

<<>>=
pronom <- lst(sie = c("ihrem", "ihrer", "ihren", "ihr", "sie", "ihre", "ihr", "die", "Frau"),
              er = c("seinem", "seiner", "seinen", "ihm", "ihn", "seine", "sein", "der", "Mann"))[[names(name)]]
project <- c(str_c(pronom[2], " Abschlussarbeit"), str_c(pronom[1], " Projektbericht"),
             str_c(pronom[2], " Hausarbeit")) |> sample(1)
betreuer <- c(str_c(pronom[2], " Betreuerin"), str_c(pronom[1], " Betreuer")) |> sample(1)

exp <- lst(pflanze = c("ein Gewächshausexperiment",
                       "ein Freilandversuch",
                       "einen Versuch in einer Klimakammer",
                       "ein Feldexperiment"),
           tier = c("ein Stallexperiment", 
                    "ein Kreuzungsexperiment",
                    "einen Leistungssteigerungsversuch"))[[names(obser)]] %>% 
  sample(1)

x1_val <- lst(pflanze = c("Düngestufen ($ctrl$, $low$, $mid$ und $high$)",
                         "Lichtstufen ($none$, $200lm$, $400lm$ und $600lm$)",
                         "Lüftungssysteme ($ctrl$, $storm$, $thunder$ und $tornado$)",
                         "Substrattypen ($torf$, $40p60n$, $30p20n$ und $70p30n$)",
                         "Bewässerungstypen ($ctrl$, $low$, $mid$ und $high$)",
                         "Genotypen ($AA$, $AB$ und $BB$)"),
           tier = c("Ernährungszusatz ($ctrl$, $fedX$ und $getIt$)", 
                    "Flüssignahrung ($ctrl$, $superIn$ und $flOw$)",
                    "Genotypen ($AA$, $AB$ und $BB$)",
                    "Elterlinie ($ctrl$, $Standard$, $Yray$ und $Xray$)",
                    "Lüftungssystem ($keins$, $storm$, $tornado$ und $thunder$)",
                    "Bestandsdichte ($standard$, $eng$, $weit$ und $kontakt$)"))[[names(obser)]] %>% 
  sample(1)

x1_val_pre <- x1_val |> str_split(" ", simplify = TRUE) |> magrittr::extract(1,1)


x2_val <- lst(pflanze = c("Düngestufen ($ctrl$, und $high$)",
                         "Lichtstufen ($none$, und $600lm$)",
                         "Lüftungssystemen und Folientunneln ($ctrl$, und $tornado$)",
                         "Substrattypen ($torf$, $70p30n$)",
                         "Bewässerungstypen ($ctrl$, und $high$)",
                         "Genotypen ($AA$, und $BB$)"),
           tier = c("Ernährungszusatz ($ctrl$ und $getIt$)", 
                    "Flüssignahrung ($ctrl$ und $flOw$)",
                    "Genotypen ($AA$ und $BB$)",
                    "Elterlinie ($ctrl$, und $Xray$)",
                    "Lüftungssystem ($keins$ und $thunder$)",
                    "Bestandsdichte ($standard$ und $kontakt$)"))[[names(obser)]] 

x2_val <- str_subset(x2_val, x1_val_pre, negate = TRUE) |> sample(1)

y_val <- lst(pflanze = c("Frischegewicht [kg/ha]",
                         "Trockengewicht [kg/ha]",
                         "Chlorophyllgehalt (SPAD-502Plus) [SPAD]",
                         "Proteingehalt [g/kg]"),
             tier = c("Schlachtgewicht [kg]", 
                      "Protein/Fettrate [\\%/kg]",
                      "Fettgehalt [\\%/kg]",
                      "Gewichtszuwachs in der 1LW"))[[names(obser)]] %>% 
  sample(1)

ques_vec <- c(str_c("In ", exp, " wurden ", obser, " mit dem Behandlung ", x1_val, " sowie der Behandlung ", x2_val, " untersucht. Es wurde als Messwert ", y_val, " bestimmt. ", name, " ahnte schon, dass es komplexer wird, als ", names(name), " mit ", project, " angefangen hat. Das es jetzt aber so kompliziert wird, hätte ", names(name), " jetzt aber auch nicht gedacht. ", name, " kratzt sich am Kopf. Eventuell muss ", names(name), " dann doch nochmal Hilfe in der statistischen Beratung holen. Jetzt versucht ", names(name), " es aber erstmal selber."),
              str_c("Wie absolut ärgerlich. Jetzt stellt sich tatsächlich heraus, dass ", betreuer, " keine Anhnung von der zweifaktoriellen ANOVA hat. Woher soll ", name, " jetzt das Wissen nehmen? Immerhin muss ", names(name), " ja noch mit ", project, " dieses Jahr fertig werden. In ", exp, " hatte ", names(name), " ", obser, " mit der Behandlung ", x1_val, " sowie der Behandlung ", x2_val, " ", ort, " untersucht. Es wurde als Messwert ", y_val, " bestimmt. Jetzt muss ", names(name), " erstmal die zweifaktorielle ANOVA verstehen."),
              str_c(name, " steht ", ort, ". Und das ist noch langweiliger als es sich anhört. Wäre es nur so spannend wie bei ", pronom[3], " Kommilitonen, die in Almería waren. Ödnis wohin man nur blickt. Oder eben ", obser, ". Ja, darum geht es in ", project, ". Und wäre das nicht noch alles genug, ist ", pronom[7], " Experiment auch noch als ", exp, " komplex geraten. Es wurde der Messwert ", y_val, " mit dem Behandlung ", x1_val, " sowie der Behandlung ", x2_val, " untersucht. 'Hmpf', denkt ", name, " und ruft 'Und jetzt!?' in die Leere.")) |> 
  sample(1)


@ 

\Sexpr{ques_vec}

<<anova-R-06-a,  echo = FALSE>>=

data_tbl <- tibble(mean = sample(c(12, 15, 17, 20, 22, 25)),
                   dose = rep(c(0.5, 1, 1.5), each = 2),
                   form = rep(c("OJ", "VC"), times = 3),
                   id = 1:6)

data_pre_tbl <- data_tbl %>%
  expand_grid(rep = 1:4)

rsp_tbl <- data_tbl %>%
  split(.$id) %>%
  map(~rnorm(4, mean = .x$mean, sd = 4))  %>%
  reduce(c) %>%
  as_tibble()

data_tbl <- bind_cols(data_pre_tbl, rsp_tbl) %>%
  dplyr::rename(gain = value) %>%
  mutate(dose = as_factor(dose))

x1_val_name <- x1_val |> str_split(" ", simplify = TRUE) |> magrittr::extract(1,1)
x2_val_name <- x2_val |> str_split(" ", simplify = TRUE) |> magrittr::extract(1,1)

interterm <- str_c(x1_val_name, ":", x2_val_name)

anova_mdl <- lm(gain ~ dose + form + dose:form, data = data_tbl) %>%
  anova 

supp_num <- 4
dose_num <- 2
int_num <- (supp_num - 1)*(dose_num-1)
@

\vspace{1ex}

Leider kennen sich \Sexpr{name} mit Berechnung einer zweifaktoriellen ANOVA überhaupt nicht aus. Deshalb braucht \Sexpr{names(name)} bei der Erstellung Ihre Hilfe! 

\begin{enumerate}
  \item Formulieren Sie die wissenschaftliche Fragestellung! \textbf{(1 Punkt)}
  \item Formulieren Sie das statistische Hypothesenpaar! \textbf{(1 Punkt)}
\item Füllen Sie die unterstehende einfaktorielle ANOVA Ergebnistabelle aus! \textbf{(3 Punkte)}
\end{enumerate}

\vspace{1Ex}

\begin{center}
  \Large
  \begin{tabular}{lccccc}
  \toprule
     & \textbf{Df} & \textbf{Sum Sq} & \textbf{Mean Sq} & \textbf{F value} & \textbf{Pr(>F)} \strut\\
    \midrule
   \textbf{\Sexpr{x1_val_name}}  & \Sexpr{supp_num-1} & \Sexpr{round(anova_mdl[[2]][1], 2)} &  &  &  \strut\\
    \textbf{\Sexpr{x2_val_name}}  & \Sexpr{dose_num-1} & \Sexpr{round(anova_mdl[[2]][2], 2)} &  &  &  \strut\\
    \textbf{\Sexpr{interterm}}  & \Sexpr{int_num} & \Sexpr{round(anova_mdl[[2]][3], 2)} &  &  &  \strut\\
   \textbf{Error}  & \Sexpr{round(anova_mdl[[1]][4], 2)} & \Sexpr{round(anova_mdl[[2]][4], 2)} &  &  &  \strut\\
\bottomrule
  \end{tabular}
\end{center}

\vspace{1Ex}

\begin{enumerate}
  \setcounter{enumi}{3}
\item Schätzen Sie den p-Wert der Tabelle ab. Begründen Sie Ihre
  Antwort! \textbf{(3 Punkte)}
\end{enumerate}
  
\begin{center}
    \Large
\begin{tabular}{lc}
  \toprule
     & $\boldsymbol{F_{\alpha = 5\%}}$ \\
\midrule
  \textbf{\Sexpr{x1_val_name}} & $4.26$ \\
  \textbf{\Sexpr{x2_val_name}} & $3.40$ \\
  \textbf{\Sexpr{interterm}} & $5.23$ \\
  \bottomrule
  \end{tabular}
\end{center}

\begin{enumerate}
  \setcounter{enumi}{4}
\item Was bedeutet ein signifikantes Ergebnis in einer zweifaktoriellen ANOVA? \textbf{(2 Punkte)}
\item Was sagt der Term \textit{\Sexpr{interterm}} aus? Interpretieren Sie das Ergebnis! \textbf{(2 Punkte)}
\end{enumerate}

