\section{Aufgabe \hfill (11 Punkte)}

\textit{Geben Sie grundsätzlich Formeln und Rechenweg zur Lösung der Teilaufgaben mit an!} \\[1Ex]
 
<<>>=
name <- par_lst$naming |> sample(1)
avatar_file <- list.files(file.path(exam_path, "avatare"), full.names = TRUE)|> 
  str_subset(name)
jahr <- par_lst$year
obser <- par_lst$obser |> sample(1) |> magrittr::extract2(1) |> sample(1)
avatar1file <- str_c("\\includegraphics[width = 1.3cm]{", avatar_file, "}")
@
 
%% --------------------------------------------------------------------
\ifcollection
\begin{flushright}
\tiny\vspace{-3Ex}
\textbf{\examinhaltstart}
\exammodulestatversuch $\;\bullet$
\exammodulebiostat
\vspace{-4Ex}
\end{flushright}
\begin{minipage}[t]{0.5\textwidth}
\Sexpr{avatar1file}
\end{minipage}
\begin{minipage}[t]{0.5\textwidth}
\hfill
\href{https://youtu.be/-yJWhI3Uy5g}{\includegraphics[width = 2cm]{img/youtube}}
\end{minipage}
\vspace{-3Ex}
\fi
%% --------------------------------------------------------------------

<<>>=
pronom <- lst(sie = c("ihrem", "ihrer", "ihren", "ihr", "sie", "ihre", "ihr", "die", "Frau"),
              er = c("seinem", "seiner", "seinen", "ihm", "ihn", "seine", "sein", "der", "Mann"))[[names(name)]]
project <- c(str_c(pronom[6], " Abschlussarbeit"), str_c(pronom[8], " Projektbericht"),
             str_c(pronom[6], " Hausarbeit")) |> sample(1)
betreuer <- c(str_c(pronom[6], " Betreuerin"), str_c(pronom[7], " Betreuer")) |> sample(1)

exp <- lst(pflanze = c("ein Gewächshausexperiment",
                       "ein Freilandversuch",
                       "einen Versuch in einer Klimakammer",
                       "ein Feldexperiment"),
           tier = c("ein Stallexperiment", 
                    "ein Kreuzungsexperiment",
                    "einen Leistungssteigerungsversuch"))[[names(obser)]] %>% 
  sample(1)

x1_val <- lst(pflanze = c("Düngestufen ($ctrl$, $low$, $mid$ und $high$)",
                         "Lichtstufen ($none$, $200lm$, $400lm$ und $600lm$)",
                         "Lüftungssysteme ($ctrl$, $storm$, $thunder$ und $tornado$)",
                         "Substrattypen ($torf$, $40p60n$, $30p20n$ und $70p30n$)",
                         "Bewässerungstypen ($ctrl$, $low$, $mid$ und $high$)",
                         "Genotypen ($AA$, $AB$ und $BB$)"),
           tier = c("Ernährungszusatz ($ctrl$, $fedX$ und $getIt$)", 
                    "Flüssignahrung ($ctrl$, $superIn$ und $flOw$)",
                    "Genotypen ($AA$, $AB$ und $BB$)",
                    "Elterlinie ($ctrl$, $Standard$, $Yray$ und $Xray$)",
                    "Lüftungssystem ($keins$, $storm$, $tornado$ und $thunder$)",
                    "Bestandsdichte ($standard$, $eng$, $weit$ und $kontakt$)"))[[names(obser)]] %>% 
  sample(1)

x1_val_pre <- x1_val |> str_split(" ", simplify = TRUE) |> magrittr::extract(1,1)


x2_val <- lst(pflanze = c("Düngestufen ($ctrl$, und $high$)",
                         "Lichtstufen ($none$, und $600lm$)",
                         "Lüftungssystemen und Folientunneln ($ctrl$, und $tornado$)",
                         "Substrattypen ($torf$, $70p30n$)",
                         "Bewässerungstypen ($ctrl$, und $high$)",
                         "Genotypen ($AA$, und $BB$)"),
           tier = c("Ernährungszusatz ($ctrl$ und $getIt$)", 
                    "Flüssignahrung ($ctrl$ und $flOw$)",
                    "Genotypen ($AA$ und $BB$)",
                    "Elterlinie ($ctrl$, und $Xray$)",
                    "Lüftungssystem ($keins$ und $thunder$)",
                    "Bestandsdichte ($standard$ und $kontakt$)"))[[names(obser)]] 

x2_val <- str_subset(x2_val, x1_val_pre, negate = TRUE) |> sample(1)

y_val <- lst(pflanze = c("Frischegewicht [kg/ha]",
                         "Trockengewicht [kg/ha]",
                         "Chlorophyllgehalt (SPAD-502Plus) [SPAD]",
                         "Proteingehalt [g/kg]"),
             tier = c("Schlachtgewicht [kg]", 
                      "Protein/Fettrate [\\%/kg]",
                      "Fettgehalt [\\%/kg]",
                      "Gewichtszuwachs in der 1LW"))[[names(obser)]] %>% 
  sample(1)

sentence_name_vec <- sentence_func(name, pronom, attr_lst[[name]])
attr_name_vec <- attr_lst[[name]]

ques_vec <-  c(str_c("In ", exp, " wurden ", obser, " mit der Behandlung ", x1_val, " sowie der Behandlung ", x2_val, " untersucht. Es wurde als Messwert ", y_val, " bestimmt. Jetzt starrt ", name, " mit auf die \\Rlogo Ausgabe einer zweifaktoriellen ANOVA. Leider starrt ", betreuer, " in der gleichen Art ", name, " zurück an. Es liegt anscheinend eine signifikante Interaktion vor? 'Das wird ein langer Nachmmittag.', denkt ", names(name), " sich und kreuselt ", pronom[3], " Mund. 'Und was machen wir jetzt?' entfährt es ", pronom[4], " überrascht entnervt. Immerhin war geht es ja um ", project, ". ", name, " hätte doch nichts mit ", obser, " machen sollen. ", obser, " -- was soll das auch bedeutendes sein? Eigentlich wollte ", name, " nachher noch einen Film schauen. ", sentence_name_vec$animal_film),
               str_c("Es ist schon kurz nach fünf und ", name, " wird langsam nervös. ", name, " wollte heute Abend noch ", pronom[6], " E-Sport Qualifikation schauen und dann zum Sport. Stattdessen versucht ", betreuer, " die Ausgabe der zweifaktoriellen ANOVA zu visualieren und zu überprüfen, ob es mit der Visualisierung der Daten als Boxplots zusammenpasst. Es liegt anscheinend eine signifikante Interaktion vor? ", name, " hatte ", ort, " ", exp, " mit ", obser, " durchgeführt. Es gab dabei zwei Behandlungen. Einmal ", x1_val, " sowie als zweite Behandlung ", x2_val, ". Gemessen wurde der Messwert ($Y$) ", y_val, ". So kompliziert kann das jetzt doch nicht sein! Eigentlich wollte ", name, " nachher noch zum Sport. ", sentence_name_vec$sport),
               str_c("'Mit der zweifaktoriellen ANOVA lässt sich die Interaktion zwischen den beiden Behandlungen nachweisen!', ", betreuer, " scheint die zweifaktoriellen ANOVA zu verstehen. Warum jetzt ", names(name), " jetzt nochmal alles wiederkäuen muss, wird ", name, " echt nicht so klar. Wenn es doch so klar ist? ", name, " war ", ort, " und hatte dort ", exp, " mit ", obser, " durchgeführt. Die Komune wo ", names(name), " untergekommen war, war cool gewesen. Nur jetzt muss eben das Experiment fertig ausgewertet werden. Es liegt anscheinend eine signifikante Interaktion vor? ", name, " hatte zwei Behandlungen auf ", obser, " angewendet. Einmal ", x1_val, " sowie als zweite Behandlung ", x2_val, ". Gemessen wurde der Messwert ($Y$) ", y_val, ". Jetzt muss das hier zu einem Ende kommen! Eigentlich wollte ", name, " nachher noch einen Film schauen. ", sentence_name_vec$animal_film)) |> 
  sample(1)

@ 

\ifcollection
\paragraph{Interaktion in der zweifaktoriellen ANOVA}
\fi

\Sexpr{ques_vec}

\vspace{1ex}

Leider kennen sich \Sexpr{name} und \Sexpr{betreuer} mit der zweifaktoriellen ANOVA überhaupt nicht aus. Geschweige denn mit der Interpretation einer Interaktion. Deshalb braucht \Sexpr{names(name)} bei der Erstellung Ihre Hilfe, sonst wird es heute Abend mit seinem Hobby \Sexpr{attr_name_vec$hobby} nichts mehr! 

\begin{enumerate}
\item Visualisieren Sie folgende mögliche Interaktionen zwischen den Behandlungen! Heben Sie die Positionen der auftretenden Interaktion (farblich) hervor! Beschriften Sie die Abbildung! \textbf{(4 Punkte)}
\begin{enumerate}
\item \underline{Keine} Interaktion liegt vor.
\item Eine \underline{schwache} Interaktion liegt vor. 
\item Eine \underline{starke} Interaktion liegt vor. 
\end{enumerate}
\item Erklären Sie den Unterschied zwischen den verschiedenen Interaktionen! \textbf{(2 Punkte)}
\item Welche statistische Maßzahl betrachten Sie für die Bewertung der Interaktion? \textbf{(1 Punkt)}
\item Schreiben Sie das Modell mit Interaktionsterm in \Rlogo für eine zweifaktorielle ANOVA! \textbf{(1 Punkt)} 
\item Skizzieren Sie die Funktion in \Rlogo für eine Post-hoc Analyse in \texttt{\{emmeans\}}! \textbf{(1 Punkt)} 
\item Wenn eine signifikante Interaktion in den Daten vorliegt, wie ist dann das weitere Vorgehen? Berücksichtigen Sie dabei die Verwendung von \texttt{\{emmeans\}}! \textbf{(2 Punkte)}
\end{enumerate}


