\section{Aufgabe \hfill (10 Punkte)}

\textit{Geben Sie grundsätzlich Formeln und Rechenweg zur Lösung der Teilaufgaben mit an!} \\[1Ex]
 
<<>>=
name <- par_lst$naming |> sample(1)
avatar_file <- list.files(file.path(exam_path, "avatare"), full.names = TRUE)|> 
  str_subset(name)
jahr <- par_lst$year
obser <- par_lst$obser |> sample(1) |> magrittr::extract2(1) |> sample(1)
avatar1file <- str_c("\\includegraphics[width = 1.3cm]{", avatar_file, "}")
@
 
%% --------------------------------------------------------------------
\ifcollection
\begin{flushright}
\tiny\vspace{-3Ex}
\textbf{\examinhaltstart}
\exammodulestatversuch $\;\bullet$
\exammodulebiostat
\vspace{-4Ex}
\end{flushright}
\begin{minipage}[t]{0.5\textwidth}
\Sexpr{avatar1file}
\end{minipage}
\begin{minipage}[t]{0.5\textwidth}
\hfill
\href{https://youtu.be/rWTyHXXlYjY}{\includegraphics[width = 2cm]{img/youtube}}
\end{minipage}
\vspace{-3Ex}
\fi
%% --------------------------------------------------------------------

<<>>=
pronom <- lst(sie = c("ihrem", "ihrer", "ihren", "ihr", "sie", "ihre", "ihr", "die", "Frau"),
              er = c("seinem", "seiner", "seinen", "ihm", "ihn", "seine", "sein", "der", "Mann"))[[names(name)]]
project <- c(str_c(pronom[6], " Abschlussarbeit"), str_c(pronom[8], " Projektbericht"),
             str_c(pronom[6], " Hausarbeit")) |> sample(1)
betreuer <- c(str_c(pronom[6], " Betreuerin"), str_c(pronom[7], " Betreuer")) |> sample(1)

exp <- lst(pflanze = c("ein Gewächshausexperiment",
                       "ein Freilandversuch",
                       "einen Versuch in einer Klimakammer",
                       "ein Feldexperiment"),
           tier = c("ein Stallexperiment", 
                    "ein Kreuzungsexperiment",
                    "einen Leistungssteigerungsversuch"))[[names(obser)]] %>% 
  sample(1)

x1_val <- lst(pflanze = c("Düngestufen ($ctrl$, $low$, $mid$ und $high$)",
                         "Lichtstufen ($none$, $200lm$, $400lm$ und $600lm$)",
                         "Lüftungssysteme ($ctrl$, $storm$, $thunder$ und $tornado$)",
                         "Substrattypen ($torf$, $40p60n$, $30p20n$ und $70p30n$)",
                         "Bewässerungstypen ($ctrl$, $low$, $mid$ und $high$)",
                         "Genotypen ($AA$, $AB$ und $BB$)"),
           tier = c("Ernährungszusatz ($ctrl$, $fedX$ und $getIt$)", 
                    "Flüssignahrung ($ctrl$, $superIn$ und $flOw$)",
                    "Genotypen ($AA$, $AB$ und $BB$)",
                    "Elterlinie ($ctrl$, $Standard$, $Yray$ und $Xray$)",
                    "Lüftungssystem ($keins$, $storm$, $tornado$ und $thunder$)",
                    "Bestandsdichte ($standard$, $eng$, $weit$ und $kontakt$)"))[[names(obser)]] %>% 
  sample(1)

x1_val_pre <- x1_val |> str_split(" ", simplify = TRUE) |> magrittr::extract(1,1)


x2_val <- lst(pflanze = c("Düngestufen ($ctrl$, und $high$)",
                         "Lichtstufen ($none$, und $600lm$)",
                         "Lüftungssystemen und Folientunneln ($ctrl$, und $tornado$)",
                         "Substrattypen ($torf$, $70p30n$)",
                         "Bewässerungstypen ($ctrl$, und $high$)",
                         "Genotypen ($AA$, und $BB$)"),
           tier = c("Ernährungszusatz ($ctrl$ und $getIt$)", 
                    "Flüssignahrung ($ctrl$ und $flOw$)",
                    "Genotypen ($AA$ und $BB$)",
                    "Elterlinie ($ctrl$, und $Xray$)",
                    "Lüftungssystem ($keins$ und $thunder$)",
                    "Bestandsdichte ($standard$ und $kontakt$)"))[[names(obser)]] 

x2_val <- str_subset(x2_val, x1_val_pre, negate = TRUE) |> sample(1)

y_val <- lst(pflanze = c("Frischegewicht [kg/ha]",
                         "Trockengewicht [kg/ha]",
                         "Chlorophyllgehalt (SPAD-502Plus) [SPAD]",
                         "Proteingehalt [g/kg]"),
             tier = c("Schlachtgewicht [kg]", 
                      "Protein/Fettrate [\\%/kg]",
                      "Fettgehalt [\\%/kg]",
                      "Gewichtszuwachs in der 1LW"))[[names(obser)]] %>% 
  sample(1)

sentence_name_vec <- sentence_func(name, pronom, attr_lst[[name]])
attr_name_vec <- attr_lst[[name]]

ques_vec <-  c(str_c("In ", exp, " wurden ", obser, " mit der Behandlung ", x1_val, " sowie der Behandlung ", x2_val, " untersucht. Es wurde als Messwert ", y_val, " bestimmt. Jetzt starrt ", name, " mit auf die \\Rlogo Ausgabe einer zweifaktoriellen ANOVA. Leider starrt ", betreuer, " in der gleichen Art ", name, " zurück an. Das wird ein langer Nachmmittag, denkt ", names(name), " sich und kreuselt ", pronom[3], " Mund. 'Und was machen wir jetzt?' entfährt es ", pronom[4], " überrascht entnervt. Immerhin war geht es ja um ", project, ". ", name, " hätte doch nichts mit ", obser, " machen sollen. ", obser, " -- was soll das auch bedeutendes sein? Eigentlich wollte ", name, " nachher noch einen Film schauen. ", sentence_name_vec$animal_film),
               str_c("Es ist schon kurz nach fünf und ", name, " wird langsam nervös. ", name, " wollte heute Abend noch ", pronom[6], " E-Sport Qualifikation schauen. Stattdessen versucht ", betreuer, " die Ausgabe der zweifaktoriellen ANOVA zu visualieren und zu überprüfen, ob es mit der Visualisierung der Daten als Boxplots zusammenpasst. ", name, " hatte ", ort, " ", exp, " mit ", obser, " durchgeführt. Es gab dabei zwei Behandlungen. Einmal ", x1_val, " sowie als zweite Behandlung ", x2_val, ". Gemessen wurde der Messwert ($Y$) ", y_val, ". So kompliziert kann das jetzt doch nicht sein! Eigentlich wollte ", name, " nachher noch zum Sport. ", sentence_name_vec$sport),
               str_c("'Mit der zweifaktoriellen ANOVA lässt sich die Interaktion zwischen den beiden Behandlungen nachweisen!', ", betreuer, " scheint die zweifaktoriellen ANOVA zu verstehen. Warum jetzt ", names(name), " jetzt nochmal alles wiederkäuen muss, wird ", name, " echt nicht so klar. Wenn es doch so klar ist? ", name, " war ", ort, " und hatte dort ", exp, " mit ", obser, " durchgeführt. Die Komune wo ", names(name), " untergekommen war, war cool gewesen. Nur jetzt muss eben das Experiment fertig ausgewertet werden. ", name, " hatte zwei Behandlungen auf ", obser, " angewendet. Einmal ", x1_val, " sowie als zweite Behandlung ", x2_val, ". Gemessen wurde der Messwert ($Y$) ", y_val, ". Jetzt muss das hier zu einem Ende kommen! Eigentlich wollte ", name, " nachher noch einen Film schauen. ", sentence_name_vec$animal_film)) |> 
  sample(1)




@ 

\ifcollection
\paragraph{Die zweifaktorielle ANOVA in \Rlogo}
\fi

\Sexpr{ques_vec}

<<anova-R-05-a,  echo = FALSE>>=

data_tbl <- tibble(mean = sample(c(12, 15, 17, 20, 22, 25)),
                   dose = rep(c(0.5, 1, 1.5), each = 2),
                   form = rep(c("OJ", "VC"), times = 3),
                   id = 1:6)

data_pre_tbl <- data_tbl %>%
  expand_grid(rep = 1:4)

rsp_tbl <- data_tbl %>%
  split(.$id) %>%
  map(~rnorm(4, mean = .x$mean, sd = 4))  %>%
  reduce(c) %>%
  as_tibble()

data_tbl <- bind_cols(data_pre_tbl, rsp_tbl) %>%
  dplyr::rename(gain = value) %>%
  mutate(dose = as_factor(dose))

anova_mdl <- lm(gain ~ dose + form + dose:form, data = data_tbl) %>%
  anova 

x1_val_name <- x1_val |> str_split(" ", simplify = TRUE) |> magrittr::extract(1,1)
x2_val_name <- x2_val |> str_split(" ", simplify = TRUE) |> magrittr::extract(1,1)


row.names(anova_mdl) <- c(x1_val_name, x2_val_name, str_c(x1_val_name, ":", x2_val_name), "Residuals")

y_val <- y_val |> str_split(" ", simplify = TRUE) |> magrittr::extract(1,1)

attr(anova_mdl, "heading")[2] <- str_c("Response: ", y_val)
anova_mdl

@

\vspace{1ex}

Leider kennt sich \Sexpr{name} mit Berechnung einer zweifaktoriellen ANOVA überhaupt nicht aus. Deshalb braucht \Sexpr{names(name)} bei der Erstellung Ihre Hilfe! 

\begin{enumerate}
  \item Formulieren Sie die wissenschaftliche Fragestellung! \textbf{(1 Punkt)}
  \item Formulieren Sie das statistische Hypothesenpaar! \textbf{(1 Punkt)}
\item Interpretieren Sie das Ergebnis der einfaktoriellen ANOVA! \textbf{(3 Punkte)} 
\item Zeichnen Sie eine Abbildung, der dem obigen Ergebnis der
  zweifaktoriellen ANOVA näherungsweise entspricht! \textbf{(5 Punkte)}
\end{enumerate}

