\section{Aufgabe \hfill (10 Punkte)}

\textit{Geben Sie grundsätzlich Formeln und Rechenweg zur Lösung der Teilaufgaben mit an!} \\[1Ex]
 
<<>>=
name <- par_lst$naming |> sample(1)
avatar_file <- list.files(file.path(exam_path, "avatare"), full.names = TRUE)|> 
  str_subset(name)
jahr <- par_lst$year
obser <- par_lst$obser
avatar1file <- str_c("\\includegraphics[width = 1.3cm]{", avatar_file, "}")
@
 
%% --------------------------------------------------------------------
\begin{minipage}[t]{0.5\textwidth}
\Sexpr{avatar1file}
\end{minipage}
\begin{minipage}[t]{0.5\textwidth}
\hfill
\href{https://youtu.be/jakM7fHyZfU}{\includegraphics[width = 2cm]{img/youtube}}\\[1Ex]
\end{minipage}
\vspace{1ex}
%% --------------------------------------------------------------------

<<>>=
pronom <- lst(sie = c("ihrem", "ihrer", "ihren", "ihr", "sie", "ihre", "ihr"),
              er = c("seinem", "seiner", "seinen", "ihm", "ihn", "seine", "sein"))[[names(name)]]
project <- c(str_c(pronom[2], " Abschlussarbeit"), str_c(pronom[1], " Projektbericht"),
             str_c(pronom[2], " Hausarbeit")) |> sample(1)
betreuer <- c(str_c(pronom[6], " Betreuerin"), str_c(pronom[7], " Betreuer")) |> sample(1)
outcome_name <- c("das Outcome ($Y$)", "den Endpunkt ($Y$)", "den Messwert ($Y$)") |> sample(1)
ort <- c("in der Uckermark", "im Oldenburger Land", "im Teuteburgerwald", "im Emsland", "im Wendland") |> sample(1)

exp <- lst(pflanze = c("ein Gewächshausexperiment",
                       "ein Freilandversuch",
                       "einen Versuch in einer Klimakammer",
                       "ein Feldexperiment"),
           tier = c("ein Stallexperiment", 
                    "ein Kreuzungsexperiment",
                    "einen Leistungssteigerungsversuch"))[[names(obser)]] %>% 
  sample(1)

x_val <- lst(pflanze = c("Pestizideinsatz [ja/nein]",
                         "Herbizideinsatz [ja/nein]",
                         "Mechanische Bearbeitung [ja/nein]",
                         "KI-gesteuert [ja/nein]"),
             tier = c("Automatische Fütterung [ja/nein]", 
                      "Klimakontrolle [ja/nein]",
                      "Außenklimakontakt [ja/nein]",
                      "Ökologisch [ja/nein]"))[[names(obser)]] %>% 
  sample(1)

y_val <- lst(pflanze = c("Frischegewicht über Zielwert [ja/nein]",
                         "Trockengewicht über Zielwert [ja/nein]",
                         "Chlorophyllgehalt unter Zielwert [ja/nein]",
                         "Proteingehalt im Zielbereich [ja/nein]"),
             tier = c("Schlachtgewicht im Zielbereich [ja/nein]", 
                      "Protein/Fettrate im Zielbereich [ja/nein]",
                      "Fettgehalt erreicht [ja/nein]",
                      "Gewichtszuwachs erreicht [ja/nein]"))[[names(obser)]] %>% 
  sample(1)

a <- round(rnorm(n = 1,
                  mean = sample(c(30, 40, 50), 1),
                  sd = sample(c(2, 4, 5), 1))) 

b <-  round(rnorm(n = 1,
                   mean = sample(c(20, 30, 40), 1),
                   sd = sample(c(2, 4, 5), 1))) 

c <-  round(rnorm(n = 1,
                   mean = sample(c(30, 40, 50), 1),
                   sd = sample(c(2, 4, 5), 1)))

d <-  round(rnorm(n = 1,
                   mean = sample(c(20, 30, 40), 1),
                   sd = sample(c(2, 4, 5), 1))) 

abcd <- a + b + c +d
ac <- a+c
bd <- b+d
ab <- a+b
cd <- c+d

effect_vec <- sample(c("ein", "kein"), 1)


ques_vec <- c(str_c("Gegeben sind folgende Randsummen in einer $2x2$ Kreuztabelle aus einem
Experiment mit $n = ", abcd, "$ Sauen. In dem Experiment wurde gemessen,
ob eine Sau nach einer Behandlung mit einem Medikament (ja/nein)
mehr als 30 Ferkel pro Jahr bekommen konnte (ja/nein).")) |> 
  sample(1)



@

\Sexpr{ques_vec}

\vspace{5Ex}

\begin{center}
  \huge
  \begin{tabular}{c|c|c|c}
     & \phantom{\textbf{Erkrankt (ja)}} & \phantom{\textbf{Erkrankt (ja)}} & \phantom{\textbf{Erkrankt (ja)}} \strut\\
    \hline
   \phantom{\textbf{Pestizid (ja)}} & \phantom{100}  & \phantom{100}  &   \Sexpr{ab}  \strut\\
    \hline
    \phantom{\textbf{Pestizid (ja)}} & \phantom{100}  & \phantom{100}  &   \Sexpr{cd}   \strut\\
    \hline
     &  \Sexpr{ac} &  \Sexpr{bd} &  \Sexpr{abcd}  \strut\\
  \end{tabular}
\end{center}

\vspace{5Ex}

Leider kennt sich \Sexpr{name} mit der Berechnung eines $\\mathcal{X}^2$-Test für kategoriale Daten überhaupt nicht aus. Deshalb braucht \Sexpr{names(name)} bei der Erstellung Ihre Hilfe!

\begin{enumerate}
  \item Formulieren Sie die wissenschaftliche Fragestellung! \textbf{(1 Punkt)}
\item Ergänzen Sie die Tabelle um die fehlenden Informationen! \textbf{(1 Punkt)} 
\item Ergänzen Sie die Felder innerhalb der $2x2$ Kreuztabelle, so dass \textit{\Sexpr{effect_vec}} signifikanter Effekt zu erwarten wäre! \textbf{(2 Punkte)}
\item Begründen Sie Ihr Vorgehen an der Formel des Chi-Quadrat-Tests. Erklären Sie Ihr Vorgehen an einem Beispiel! \textbf{(2 Punkte)}
\item Visualisieren Sie den Zusammenhang zwischen den beiden kategorialen Variablen! \textbf{(2 Punkte)}
\item Was ist die Mindestanzahl an Beobachtungen je Zelle? Wenn in einer der Zellen weniger Beobachtungen auftreten, welchen Test können Sie anstatt des Standard Chi-Quadrat-Tests anwenden? \textbf{(2 Punkte)}
\end{enumerate}
