\section{Aufgabe \hfill (10 Punkte)}

\textit{Geben Sie grundsätzlich Formeln und Rechenweg zur Lösung der Teilaufgaben mit an!} \\[1Ex]
 
<<>>=
name <- par_lst$naming |> sample(1)
avatar_file <- list.files(file.path(exam_path, "avatare"), full.names = TRUE)|> 
  str_subset(name)
jahr <- par_lst$year
obser <- par_lst$obser |> sample(1) |> magrittr::extract2(1) |> sample(1)
avatar1file <- str_c("\\includegraphics[width = 1.3cm]{", avatar_file, "}")
@
 
%% --------------------------------------------------------------------
\begin{minipage}[t]{0.5\textwidth}
\Sexpr{avatar1file}
\end{minipage}
\begin{minipage}[t]{0.5\textwidth}
\hfill
\href{https://youtu.be/VAqiUdV4WQ0}{\includegraphics[width = 2cm]{img/youtube}}
\end{minipage}
\vspace{-3ex}
%% --------------------------------------------------------------------


<<>>=
pronom <- lst(sie = c("ihrem", "ihrer", "ihren", "ihr", 
                      "sie", "ihre", "ihr", "die", "Frau"),
              er = c("seinem", "seiner", "seinen", "ihm", 
                     "ihn", "seine", "sein", "der", "Mann"))[[names(name)]]
project <- c(str_c(pronom[2], " Abschlussarbeit"), str_c(pronom[1], " Projektbericht"),
             str_c(pronom[2], " Hausarbeit")) |> sample(1)
betreuer <- c(str_c(pronom[2], " Betreuerin"), str_c(pronom[1], " Betreuer")) |> sample(1)
outcome_name <- c("das Outcome ($Y$)", "den Endpunkt ($Y$)", "den Messwert ($Y$)") |> sample(1)
ort <- c("in der Uckermark", "im Oldenburger Land", "im Teuteburgerwald", "im Emsland", "im Wendland") |> sample(1)

exp <- lst(pflanze = c("ein Gewächshausexperiment",
                       "ein Freilandversuch",
                       "einen Versuch in einer Klimakammer",
                       "ein Feldexperiment"),
           tier = c("ein Stallexperiment", 
                    "ein Kreuzungsexperiment",
                    "einen Leistungssteigerungsversuch"))[[names(obser)]] %>% 
  sample(1)

x_val <- lst(pflanze = c("durschnittlichen Niederschlag [ml/w]",
                         "durchschnittlicher Regenwurmdichte [Anzahl/l]",
                         "durchschnittlichen Anteil an Ton [\\%/l]",
                         "durchschnittliche UV Einstrahlung [UV/d]"),
             tier = c("durchschnittlichen Bewegungsscore [Movement/h]", 
                      "durchschnittlicher Tagestemperatur [C/d]",
                      "mittlerer Anzahl an weißen Blutkörperchen [LEU/ml]",
                      "mittlerer Eisenkonzentration [Fe/ml]"))[[names(obser)]] %>% 
  sample(1)

y_val <- lst(pflanze = c("Frischegewicht [kg/ha]",
                         "Trockengewicht [kg/ha]",
                         "Chlorophyllgehalt (SPAD-502Plus) [SPAD]",
                         "Proteingehalt [g/kg]"),
             tier = c("Schlachtgewicht [kg]", 
                      "Protein/Fettrate [\\%/kg]",
                      "Fettgehalt [\\%/kg]",
                      "Gewichtszuwachs in der 1LW"))[[names(obser)]] %>% 
  sample(1)

effect <- c("ein", "kein") |> sample(1)

sentence_name_vec <- sentence_func(name, pronom, attr_lst[[name]]) 

ques_vec <- c(str_c(sentence_name_vec$sweet_music, " Jetzt heißt es aber erstmal auf was anderes konzentrieren. ", name, " möchte gerne den Zusammenhang zwischen ", x_val, " und ", y_val, " im Kontext von ", obser, " herausfinden. Hierfür hat ", name , " ", exp, " ", ort, " durchgeführt. Nach einigen unvorgesehenen Ereignissen hat ", names(name), " es geschafft folgende Datentabelle zu erstellen. ", sentence_name_vec$flaw, " Aber das steht auch nicht im Zentrum. Nun stellt sich die Frage für ", pronom[5], ", ob es überhaupt einen Zusammenhang zwischen den gemessenen Variablen gibt. Deshalb möchte ", name, " als erstes eine explorative Datenanalyse durchführen. Dann was anderes. ", sentence_name_vec$animal_film),
              str_c(name, " liest laut: 'Wenn zwei kontinuierliche Variablen vorliegen, können diese in einer exploartiven Datenanalyse...'. ", name , " stoppt. ", sentence_name_vec$sweet_music, " Was waren noch gleich kontinuierliche Variablen? In ", project, " hatte ", names(name) , " ", exp, " ", ort, " durchgeführt. Dabei ging es um den Zusammenhang zwischen ", y_val, " und ", x_val, " im groben Kontext von ", obser, ". Nun stellt sich die Frage für ", pronom[5], ", ob es überhaupt einen Zusammenhang zwischen den gemessenen Variablen gibt. Dafür war eine explorative Datenanalyse gut! ", sentence_name_vec$flaw, " Dann was anderes. ", sentence_name_vec$animal_film),
              str_c("Wenn es nach ", name , " ginge, wäre ", names(name) , " schon längst fertig mit ", project, ". Geht es aber nicht. ", sentence_name_vec$sweet_music, " In ", project, " hatte ", names(name) , " ", exp, " ", ort, " durchgeführt. Nach der Meinung ", betreuer, " sieht das jedoch etwas anders aus. Jetzt soll ", names(name) , " doch noch eine explorative Datenanalyse für den Zusammenhang zwischen ", x_val, " und ", y_val, " in ", obser, " durchführen. Wie nervig! ", sentence_name_vec$flaw, " Da zwei kontinuierliche Variablen vorliegen, geht die explorative Datenanalyse leider nicht mit Boxplots oder Barplots. Dann was anderes. ", sentence_name_vec$animal_film)) |> 
  sample(1)



@

\paragraph{Visualisierung des Scatterplots}

\Sexpr{ques_vec}

<<scatter-01, results='asis', echo = FALSE>>=
x_val <- str_replace(x_val, "\\\\", "")
y_val <- str_replace(y_val, "\\\\", "")

data_tbl <- tibble(x = round(rnorm(sample(9:12, 1), sample(c(15, 20, 25), 1), sample(c(2, 4, 6), 1)), 1),
                   y = round(sample(c(2:10), 1) + sample(c(0.5, 0.75, 1, 1.15, 1.25), 1) * x + rnorm(length(x), 0, 2), 1)) |>   set_names(sample(c(str_replace(x_val, "^\\w{1}", toupper), 
                     str_replace(y_val, "^\\w{1}", toupper))))

kable(data_tbl, booktabs = TRUE, align = "c") %>% 
  kable_styling(latex_options = "hold_position")
@

Leider kennt sich \Sexpr{name} mit der Erstellung einer explorativen Datenanalyse für kontinuierliche Daten überhaupt nicht aus. Deshalb braucht \Sexpr{names(name)} bei der Erstellung Ihre Hilfe!

\begin{enumerate}
\item Erstellen Sie eine Visualisierung für die Datentabelle. Beschriften Sie
  die Achsen entsprechend! \textbf{(4 Punkte)}
\item Schätzen Sie eine Gerade durch die Punkte! \textbf{(1 Punkt)}
\item Beschriften Sie die Gerade mit den gängigen statistischen Maßzahlen! Geben Sie die numerischen Zahlenwerte mit an! \textbf{(3 Punkte)}
\item Wenn \textit{\Sexpr{effect}} Effekt von $x$ auf $y$ vorhanden wäre, wie würde die Gerade verlaufen und welche Werte würden die statistischen Maßzahlen annehmen? \textbf{(2 Punkt)}
\end{enumerate}
