\section{Aufgabe \hfill (10 Punkte)}

\textit{Geben Sie grundsätzlich Formeln und Rechenweg zur Lösung der Teilaufgaben mit an!} \\[1Ex]
 
<<>>=
name <- par_lst$naming |> sample(1)
avatar_file <- list.files(file.path(exam_path, "avatare"), full.names = TRUE)|> 
  str_subset(name)
jahr <- par_lst$year
obser <- par_lst$obser |> sample(1) |> magrittr::extract2(1) |> sample(1)
avatar1file <- str_c("\\includegraphics[width = 1.3cm]{", avatar_file, "}")
@
 
%% --------------------------------------------------------------------
\begin{minipage}[t]{0.5\textwidth}
\Sexpr{avatar1file}
\end{minipage}
\begin{minipage}[t]{0.5\textwidth}
\hfill
\href{https://youtu.be/t_1KL77mfmg}{\includegraphics[width = 2cm]{img/youtube}}
\end{minipage}
\vspace{-3ex}
%% --------------------------------------------------------------------

<<>>=
pronom <- lst(sie = c("ihrem", "ihrer", "ihren", "ihr", 
                      "sie", "ihre", "ihr", "die", "Frau"),
              er = c("seinem", "seiner", "seinen", "ihm", 
                     "ihn", "seine", "sein", "der", "Mann"))[[names(name)]]
project <- c(str_c(pronom[2], " Abschlussarbeit"), str_c(pronom[1], " Projektbericht"),
             str_c(pronom[2], " Hausarbeit")) |> sample(1)
betreuer <- c(str_c(pronom[6], " Betreuerin"), str_c(pronom[7], " Betreuer")) |> sample(1)
outcome_name <- c("das Outcome ($Y$)", "den Endpunkt ($Y$)", "den Messwert ($Y$)") |> sample(1)
ort <- c("in der Uckermark", "im Oldenburger Land", "im Teuteburgerwald", "im Emsland", "im Wendland") |> sample(1)

exp <- lst(pflanze = c("ein Gewächshausexperiment",
                       "ein Freilandversuch",
                       "einen Versuch in einer Klimakammer",
                       "ein Feldexperiment"),
           tier = c("ein Stallexperiment", 
                    "ein Kreuzungsexperiment",
                    "einen Leistungssteigerungsversuch"))[[names(obser)]] %>% 
  sample(1)

x_val <- lst(pflanze = c("Pestizideinsatz [ja/nein]",
                         "Herbizideinsatz [ja/nein]",
                         "Mechanische Bearbeitung [ja/nein]",
                         "KI-gesteuert [ja/nein]"),
             tier = c("Automatische Fütterung [ja/nein]", 
                      "Klimakontrolle [ja/nein]",
                      "Außenklimakontakt [ja/nein]",
                      "Ökologisch [ja/nein]"))[[names(obser)]] %>% 
  sample(1)

y_val <- lst(pflanze = c("Frischegewicht über Zielwert [ja/nein]",
                         "Trockengewicht über Zielwert [ja/nein]",
                         "Chlorophyllgehalt unter Zielwert [ja/nein]",
                         "Proteingehalt im Zielbereich [ja/nein]"),
             tier = c("Schlachtgewicht im Zielbereich [ja/nein]", 
                      "Protein/Fettrate im Zielbereich [ja/nein]",
                      "Fettgehalt erreicht [ja/nein]",
                      "Gewichtszuwachs erreicht [ja/nein]"))[[names(obser)]] %>% 
  sample(1)

effect <- c("ein", "kein") |> sample(1)

sentence_name_vec <- sentence_func(name, pronom, attr_lst[[name]]) 

ques_vec <- c(str_c(sentence_name_vec$animal_film, " Aber Ablenkung hilft nur begrenzt. 'Uff!', denkt sich ", name, ". Jetzt hat ", names(name), " doch tatsächlich zwei kategoriale Variablen in ", project, " gemessen. Zum einen die Behandlung ", x_val, " und zum anderen die Messung ", y_val, " im Kontext von ", obser, ". Hierfür hat ", names(name) , " ", exp, " ", ort, " durchgeführt. Jetzt möchte ", name, " die Daten einmal in einer explorativen Datenanalyse darstellen. Danach kann ", names(name), " dann über den passenden statistischen Test nachdenken. Dabei unterstützt ", betreuer, " diesen Ansatz bevor es in der Datenanalyse weiter geht. So schön wie so gut. ", sentence_name_vec$flaw),
              str_c("Zwei kategoriale Variablen darzustellen ist nicht so einfach. ", name, " hatte erst über einen Mittelwert nachgedacht, dann aber die Idee verworfen. Wäre da nicht noch was anderes. ", sentence_name_vec$flaw, " Dabei hatte ", names(name), " sich in ", exp, " ", ort, " zum einen die Behandlung ", x_val, " und zum anderen die Messung ", y_val, " im Kontext von ", obser, " angeschaut. Jetzt möchte ", betreuer, " erstmal die langen Tabellen mit ja/nein in einer explorativen Datenanalyse zusammengefasst bekommen. Sonst geht es bei ", project, " nicht weiter. Was super nervig ist. ", sentence_name_vec$sport),
              str_c("In ", exp, " ", ort, " hatte ", name, " sich zum einen die Behandlung ", x_val, " und zum anderen die Messung ", y_val, " im Kontext von ", obser, " angeschaut. Nun steht ", name, " vor dem Problem, dass ", names(name), " zwei kategoriale Variablen in ", project, " gemessen hat. Dazu kommt dann noch was anderes. ", sentence_name_vec$flaw, " Da ", betreuer, " erstmal die langen Tabellen mit ja/nein in einer explorativen Datenanalyse zusammengefasst und präsentiert bekommen möchte bevor es überhaupt weitergeht, muss ", names(name), " jetzt eine Lösung finden. Was alles auch nicht einfacher macht. Am liebsten würde ", names(name), " ja was anderes machen. ", sentence_name_vec$hobby)) |> 
  sample(1)

@

\paragraph{Visualisierung des Mosaicplots}

\Sexpr{ques_vec}

<<mosaic-01, results='asis', echo = FALSE>>=
x_val <- str_replace(x_val, "\\[ja/nein\\]$", "") |> str_trim()
y_val <- str_replace(y_val, "\\[ja/nein\\]$", "") |> str_trim()
data_tbl <- rbind(tibble(ja = round(rnorm(n = sample(c(14, 16, 18), 1),
                                         mean = sample(c(18, 20, 22), 1),
                                         sd = sample(c(2, 3, 4), 1)))) %>%
                  gather,
                  tibble(nein = round(rnorm(n = sample(c(14, 16, 18), 1),
                                         mean = sample(c(18, 20, 22), 1),
                                         sd = sample(c(2, 3, 4), 1)))) %>%
                  gather) %>%
  set_names(c("pesticide", "rsp")) %>%
  mutate(infected = ifelse(rsp >= 20, "ja", "nein")) %>%
  select(-rsp) %>% 
  sample_n(size = nrow(.)) |> 
  set_names(sample(c(str_replace(x_val, "^\\w{1}", toupper), 
                     str_replace(y_val, "^\\w{1}", toupper))))

@

\vspace{1Ex}

\begin{center}
\begin{minipage}[t]{0.45\textwidth}
%\small
\begin{center}
<<mosaic-01-tab-a, results='asis', echo = FALSE>>=
kable(data_tbl[1:(nrow(data_tbl)/2),], booktabs = TRUE, align = "p{2.5cm}p{2.5cm}", format = "latex") 
@
\end{center}
\end{minipage}
\begin{minipage}[t]{0.45\textwidth}
%\small
\begin{center}
<<mosaic-01-tab-b, results='asis', echo = FALSE>>=
kable(data_tbl[(nrow(data_tbl)/2+1):(nrow(data_tbl)),], booktabs = TRUE, align = "p{2.5cm}p{2.5cm}", 
      format = "latex") 
@
\end{center}
\end{minipage}
\end{center}

\vspace{2Ex}

Leider kennt sich \Sexpr{name} mit der Erstellung einer explorativen Datenanalyse für kategoriale Daten überhaupt nicht aus. Deshalb braucht \Sexpr{names(name)} bei der Erstellung Ihre Hilfe!

\begin{enumerate}
\item Stellen Sie den Zusammenhang zwischen den beiden kategorialen Variablen in einer zusammenfassenden Tabelle dar! \textbf{(3 Punkte)}
\item Visualisieren Sie den Zusammenhang zwischen den beiden kategorialen Variablen! \textbf{(3 Punkte)}
\item Berechnen Sie die Verhältnisse in der Visualisierung! Welche Annahme haben Sie getroffen? \textbf{(2 Punkte)}
\item Wenn \textit{\Sexpr{effect}} Effekt von der Behandlung vorliegen würde, wie würde die Tabelle und die Visualisierung aussehen? \textbf{(2 Punkt)}
\end{enumerate}
