\section{Aufgabe \hfill (20 Punkte)}

\textit{Geben Sie grundsätzlich Formeln und Rechenweg zur Lösung der Teilaufgaben mit an!} \\[1Ex]
 
<<>>=
name <- par_lst$naming |> sample(1)
avatar_file <- list.files(file.path(exam_path, "avatare"), full.names = TRUE)|> 
  str_subset(name)
jahr <- par_lst$year
obser <- par_lst$obser |> sample(1) |> magrittr::extract2(1) |> sample(1)
avatar1file <- str_c("\\includegraphics[width = 1.3cm]{", avatar_file, "}")
@
 
%% --------------------------------------------------------------------
\ifcollection
\begin{flushright}
\tiny\vspace{-3Ex}
\textbf{\examinhaltstart}
\exammodulebiostat
\vspace{-4Ex}
\end{flushright}
\begin{minipage}[t]{0.5\textwidth}
\Sexpr{avatar1file}
\end{minipage}
\begin{minipage}[t]{0.5\textwidth}
\hfill
\href{https://youtu.be/C9skfFRTHhI}{\includegraphics[width = 2cm]{img/caution}}
\end{minipage}
\fi
%% --------------------------------------------------------------------

<<>>=
pronom <- lst(sie = c("ihrem", "ihrer", "ihren", "ihr", "sie", "ihre", "ihr", "die", "Frau"),
              er = c("seinem", "seiner", "seinen", "ihm", "ihn", "seine", "sein", "der", "Mann"))[[names(name)]]
betreuer <- c(str_c(pronom[6], " Betreuerin"), str_c(pronom[7], " Betreuer")) |> sample(1)

paper <- c("Sánchez, M., et al. (2022). Hoverfly pollination enhances yield and fruit quality in mango under protected cultivation",
           "Petersen, F., et al. (2022). Influence of light intensity and spectrum on duckweed growth and proteins in a small-scale, re-circulating indoor vertical farm",
           "Selle, P. H., et al. (2010). Implications of sorghum in broiler chicken nutrition",
           "Wu, G., et al. (2004). Arginine nutrition in neonatal pigs",
           "Edgar, G., J., et al. (2024) Stock assessment models overstate sustainability of the world’s fisheries") |> 
  set_names(c("mango", "duckweed", "chicken", "pigs", "fish")) |> sample(1)

sentence_name_vec <- sentence_func(name, pronom, attr_lst[[name]])
attr_name_vec <- attr_lst[[name]]

ques_vec <- c(str_c(name, " hält die wissenschaftliche Veröffentlichung \\textit{", paper, "} unter einem Schnaufen in die Luft. 'Worum geht es denn eigentlich in dieser Arbeit?', fragt ", names(name), " stirnrunzelnd und wirft die Arme in die Luft, da hilft dann auch nicht mehr die beruhigende Wirkung von ", attr_name_vec$music, ". ", name, " soll die Veröffentlichung nutzen um das eigene Experiment zu planen. Als eine Vorlage sozusagen. Daher möchte ", betreuer, ", dass ", names(name), " einmal die Veröffentlichung sinnvoll zusammenfasst. Das sollte dann doch etwas aufwendiger werden. Das wird dann vermutlich heute Abend nichts mehr mit ", pronom[1], " Hobby ", attr_name_vec$hobby, ". ", str_replace(attr_name_vec$animal, "^\\w{1}", toupper), " schaut mitleidig."),
              str_c("Vor dem Start der eigenen Arbeit möchte ", betreuer, ", dass ", name, " einmal die wissenschaftliche Veröffentlichung \\textit{", paper, "} sinnvoll zusammenfasst. Dann würde die eigene Arbeit auch leichter von der Hand gehen und ", name, " hätte dann schon eine Vorlage. 'Das ist jetzt aber umfangreicher als gedacht!', schnauft ", names(name), " und runzelt die Stirn. Im Hintergrund spielt viel zu leise ", attr_name_vec$music, ". Das wird dann vermutlich heute Abend nichts mehr mit ", pronom[1], " Hobby ", attr_name_vec$hobby, ". ", str_replace(attr_name_vec$animal, "^\\w{1}", toupper), " schaut mitleidig."),
              str_c("'Uff', denkt ", name, ". Das ist jetzt doch etwas umfangreicher. ", name, " soll die wissenschaftliche Veröffentlichung \\textit{", paper, "} einmal zusammenfassen. Die Arbeit soll als eine Vorlage für ", pronom[6], " eigene Arbeit dienen. Daher möchte ", betreuer, ", dass ", names(name), " einmal die Veröffentlichung in einer PowerPoint Präsentation zusammenfasst. 'Das ist jetzt aber doch umfangreicher als gedacht.', mault ", name, " in sich hinein. Schnell nochmal ein paar ", attr_name_vec$sweet, " zur Stärkung gegessen. Das wird dann vermutlich heute Abend nichts mehr mit ", pronom[1], " Hobby ", attr_name_vec$hobby, ". ", str_replace(attr_name_vec$animal, "^\\w{1}", toupper), " schaut mitleidig.")) |> 
  sample(1)



@

\ifcollection
\paragraph{Zerforschen einer wissenschaftlichen Veröffentlichung}
\fi

\Sexpr{ques_vec}\\

Leider kennt sich \Sexpr{name} mit dem Lesen einer wissenschaftlichen Veröffentlichung mit Fokus auf die Statistik überhaupt nicht aus. Deshalb braucht \Sexpr{names(name)} bei der Erstellung Ihre Hilfe! Glücklicherweise kennen Sie die wissenschaftliche Veröffentlichung schon im Detail und können sofort helfen.

\begin{enumerate}
  \setcounter{enumi}{0}
  \item Erläutern Sie die wissenschaftliche Fragestellung der wissenschaftlichen Veröffentlichung anhand des OCAR Prinzips nach Schimel (2012)\footnote{Schimel, J. (2012). Writing science: how to write papers that get cited and proposals that get funded. OUP USA.} \textbf{(4 Punkte)}
  \item Nennen Sie die untersuchten Endpunkte in der wissenschaftlichen Veröffentlichung! Wie lautet der primäre Endpunkt? \textbf{(2 Punkte)} 
\item Erstellen Sie das statistische Modell in der in \Rlogo üblichen Schreibweise! \textbf{(2 Punkte)}
  \item Nennen Sie eine Auswahl an bedeutenden statistischen Maßzahlen in der wissenschaftlichen Veröffentlichung! \textbf{(1 Punkt)}
  \item Interpretieren Sie die Hauptaussage der wissenschaftlichen Veröffentlichung hinsichtlich der Signifkanz für den primären Endpunkt! \textbf{(2 Punkte)}
  \item Interpretieren Sie die Hauptaussage der wissenschaftlichen Veröffentlichung hinsichtlich der Effektstärke für den primären Endpunkt! \textbf{(2 Punkte)}
  \item Diskutieren Sie die ökonomische Relevanz der Hauptaussage der wissenschaftlichen Veröffentlichung im Bezug auf Signifikanz und Effektstärke für den primären Endpunkt! \textbf{(1 Punkt)}
  \item Skizzieren Sie für den primären Endpunkt den sich ergebenden Datensatz in \Rlogo für eine ausgewählte Abbildung! \textbf{(2 Punkte)}
\item Skizzieren Sie einen möglichen Versuchsplan für den primären Endpunkt! \textbf{(2 Punkte)}
  \item Schätzen Sie die benötigte Fallzahl für ein zukünftiges Experiment anhand der Ergebnisse in der wisenschaftlichen Veröffentlichung für den primären Endpunkt! \textbf{(2 Punkte)}
\end{enumerate}
