\section{Aufgabe \hfill (2 Punkte)}

<<>>=
type <- c("des p-Wertes", "der berechneten Teststatistik", "des 95\\%-Konfidenzintervalls") %>% sample(1)
@ 

Welche Aussage über die Entscheidung anhand \Sexpr{type} gegen die
Nullhypothese ist richtig?

<<mc-statistisches-testen-012, results='asis', echo = FALSE>>=

questions_vec <- c('Ist $Pr(D|H_0)$ kleiner als das Signifikanzniveau $\\alpha$ gleich $5\\%$ dann wird die Nullhypothese $H_0$ abgelehnt.',
                   'Ist $T_{D}$ h{\"o}her als der kritische Wert $T_{\\alpha = 5\\%}$ dann wird die Nullhypothese $H_0$ abgelehnt.',
                   'Ist in dem 95\\%-Konfidenzintervall nicht die Null enthalten dann wird die Nullhypothese $H_0$ abgelehnt.',
                   str_c('Anhand ', type, ' lässt sich wie folgt eine Entscheidung treffen. Liegt der Wert über oder gleich dem Signifikanzniveau $\\alpha$ dann kann die Nullhypothese abgelehnt werden.'),
                   str_c('Anhand ', type, ' lässt sich wie folgt eine Entscheidung treffen. Liegt der Wert in dem Signifikanzniveauintervall $\\alpha$ dann kann die Nullhypothese abgelehnt werden.')                   
                   ) %>%
  sample


@

\begin{enumerate}
\item [\textbf{A} \msquare] \Sexpr{questions_vec[1]}
\item [\textbf{B} \msquare] \Sexpr{questions_vec[2]}
\item [\textbf{C} \msquare] \Sexpr{questions_vec[3]}
\item [\textbf{D} \msquare] \Sexpr{questions_vec[4]}
\item [\textbf{E} \msquare] \Sexpr{questions_vec[5]}
\end{enumerate}
