\section{Aufgabe \hfill (2 Punkte)}

%% --------------------------------------------------------------------
\ifcollection
\begin{flushright}
\tiny\vspace{-2Ex}
\textbf{\examinhaltstart}
\exammodulemathstat $\;\bullet$
\exammodulestat $\;\bullet$
\exammodulestatbbv $\;\bullet$
\exammodulestatversuch\\
\exammodulelanddaten $\;\bullet$
\exammodulebiostat
\vspace{-1Ex}
\end{flushright}
\fi
%% --------------------------------------------------------------------


<<>>=
ques_vec <- c('Wissenschaft und Daten sind eng miteinander verknüpft. Bevor wir aber mit Wissenschaft beginnen können brauchen wir Daten auf denen wir eine Aussage aufbauen können. Welche Aussage zu Daten ist richtig?',
              'Sie wollen Ihren Datensatz in \\Rlogo einlesen und stehen nun vor einem Problem. Was sind eigentlich Daten und was machen Daten aus? Welche Aussage zu Daten ist richtig?',
              '"It is a capital mistake to theorize before one has data. Insensibly one begins to twist facts to suit theories, instead of theories to suit facts.", besagt das Zitat von Sherlock Holmes. Aber was sind nun Daten und welche Aussage ist richtig?') |>  sample(1)
@

\Sexpr{ques_vec}

<<mc-programming-01, results='asis', echo = FALSE>>=

right_vec <- c('Daten sind in Zahlen gegossene Beobachtungen. Darin liegt auch die Schwierigkeit Beobachtungen, die meist keine reinen Zahlen oder Werte sind, in eine Zahl zu übersetzen.',
               'Wir beobachten verschiedene Dinge in der Natur. Diese Beobachtungen sind selten reine Zahlen. Daher müssen wir unsere Beobachtungen erstmal in Zahlen übersetzen. Diese Übersetzung der Beobachtungen in Zahlen sind Daten.',
               'Wenn wir etwas beobachten, dann müsen wir die Beobachtungen als Zahlen abspeichern. Das Übersetzen von Beobachtungen in Zahlen sind Daten.') |> sample(1)

wrong_vec <- c('Daten sind Zahlen in Excel.',
               'Daten sind Beobachtungen, die keine Entsprechung in der Realität haben. Deshalnb sind alle Daten fehlerhaft.',
               'Wir beobachten verschiedene Personen und Dinge in der Rwalität und ziehen daraus unsere Schlüsse. Der Schluß sind die Daten.',
               'Zahlen sind Daten. Zahlen sind Beobachtungen. Daher sind Daten Beobachtungen, die wir machen. Auf die Zaheln kann daher verzichtet werden.',
               '\\Rlogo ist nicht in der Lage Beobachtungen zu verarbeiten. Wir nutzen daher generative KI (z.B. ChatGPT) um aus Beobachtungen Daten in Excel zu generieren.',
               'Wenn wir etwas beobachten, dann kann die Beobachtung falsch sein. Die Übersetzung in Daten kann dann die Lösung und als Korrektur für unsere Beobachtungen sein.') %>%
  sample(4)

questions_vec <- c(right_vec,
                   wrong_vec) %>%
  sample


@

\begin{enumerate}
\item [\textbf{A} \msquare] \Sexpr{questions_vec[1]}
\item [\textbf{B} \msquare] \Sexpr{questions_vec[2]}
\item [\textbf{C} \msquare] \Sexpr{questions_vec[3]}
\item [\textbf{D} \msquare] \Sexpr{questions_vec[4]}
\item [\textbf{E} \msquare] \Sexpr{questions_vec[5]}
\end{enumerate}
