\section{Aufgabe \hfill (2 Punkte)}

<<>>=

variable_vec <- c("n_1 = n_2", "n_1 < n_2",
                  "s^2_1 = s^2_2", "s^2_1 \\neq s^2_2") %>%
  sample(1)

ques_vec <- c(str_c('Sie haben das abstrakte Modell $Y \sim X$ mit $X$ als Faktor mit zwei Leveln vorliegen. Welche Aussage über ', variable_vec, ' ist richtig?'),
              '',
              '') |>  sample(1)
@

\Sexpr{ques_vec}

<<mc-balance-01, results='asis', echo = FALSE>>=

right_vec <- c("Es handelt sich um ein balanciertes Design.",
               "Es handelt sich um ein unbalanciertes Design.",
               "Es liegt Varianzhetrogenität vor.",
               "Es liegt Varianzhomogenität vor.") |> sample(4)

wrong_vec <- c("Es handelt sich um abhängige Beobachtungen.") %>%
  sample(1)

questions_vec <- c(right_vec,
                   wrong_vec) %>%
  sample

@

\begin{enumerate}
\item [\textbf{A} \msquare] \Sexpr{questions_vec[1]}
\item [\textbf{B} \msquare] \Sexpr{questions_vec[2]}
\item [\textbf{C} \msquare] \Sexpr{questions_vec[3]}
\item [\textbf{D} \msquare] \Sexpr{questions_vec[4]}
\item [\textbf{E} \msquare] \Sexpr{questions_vec[5]}
\end{enumerate}
