\section{Aufgabe \hfill (2 Punkte)}

Welche Aussage {\"u}ber den t-Test im Allgmeinen ist richtig? 

<<mc-ttest-01, results='asis', echo = FALSE>>=

questions_vec <- c('Der t-Test vergleicht die Varianzen von mindestens zwei oder mehr Gruppen',
                   'Der t-Test testet generell zu einem erh{\"o}hten $\\alpha$-Niveau von 20\\%.',
                   'Der t-Test vergleicht die Mittelwerte von zwei Gruppen.',
                   'Der t-Test vergleicht die Mittelwerte von zwei Gruppen unter der strikten Annahme von Varianzhomogenit{\"a}t. Sollte keine Varianzhomogenit{\"a}t vorliegen, so gibt es keine M{\"o}glichkeit den t-Test in einer Variante anzuwenden.',
                   'Der t-Test ist ein Vortest der ANOVA und basiert daher auf dem Vergleich von Streuungsparametern') %>%
  sample


@

\begin{enumerate}
\item [\textbf{A} \msquare] \Sexpr{questions_vec[1]}
\item [\textbf{B} \msquare] \Sexpr{questions_vec[2]}
\item [\textbf{C} \msquare] \Sexpr{questions_vec[3]}
\item [\textbf{D} \msquare] \Sexpr{questions_vec[4]}
\item [\textbf{E} \msquare] \Sexpr{questions_vec[5]}
\end{enumerate}
