\section{Aufgabe \hfill (10 Punkte)}

\textit{Geben Sie grundsätzlich Formeln und Rechenweg zur Lösung der Teilaufgaben mit an!} \\[1Ex]
 
<<>>=
name <- par_lst$naming |> sample(1)
name_sec <- str_subset(par_lst$naming, name, negate = TRUE) |> sample(1)
avatar_file <- list.files(file.path(exam_path, "avatare"), full.names = TRUE) |> 
  str_subset(str_c(name, name_sec, sep = "|"))
jahr <- par_lst$year
obser <- par_lst$obser
avatar1file <- str_c("\\includegraphics[width = 1.3cm]{", avatar_file[1], "}")
avatar2file <- str_c("\\includegraphics[width = 1.3cm]{", avatar_file[2], "}")
@
 
%% --------------------------------------------------------------------
\begin{minipage}[t]{0.5\textwidth}
\Sexpr{avatar1file}\hspace{-4mm}\Sexpr{avatar2file}
\end{minipage}
\begin{minipage}[t]{0.5\textwidth}
\hfill
\href{https://youtu.be/xq29O8qDrg0}{\includegraphics[width = 2cm]{img/youtube}}
\end{minipage}
\vspace{1ex}
%% --------------------------------------------------------------------

<<>>=
pronom <- lst(sie = c("ihrem", "ihrer", "ihren", "ihr", "sie", "ihre", "ihr", "die", "Frau"),
              er = c("seinem", "seiner", "seinen", "ihm", "ihn", "seine", "sein", "der", "Mann"))[[names(name)]]
project <- c(str_c(pronom[6], " Abschlussarbeit"), str_c(pronom[8], " Projektbericht"),
             str_c(pronom[6], " Hausarbeit")) |> sample(1)
betreuer <- c(str_c(pronom[6], " Betreuerin"), str_c(pronom[7], " Betreuer")) |> sample(1)

exp <- lst(pflanze = c("ein Gewächshausexperiment",
                       "ein Freilandversuch",
                       "einen Versuch in einer Klimakammer",
                       "ein Feldexperiment"),
           tier = c("ein Stallexperiment", 
                    "ein Kreuzungsexperiment",
                    "einen Leistungssteigerungsversuch"))[[names(obser)]] %>% 
  sample(1)

x_val <- lst(pflanze = c("Düngestufen ($ctrl$, $low$, $mid$ und $high$)",
                         "Lichtstufen ($none$, $200lm$, $400lm$, $600lm$, $700lm$ und $800lm$)",
                         "Lüftungssysteme ($ctrl$, $storm$, $thunder$ und $tornado$)",
                         "Substrattypen ($kompost$, $torf$, $40p60n$, $30p20n$ und $70p30n$)",
                         "Bewässerungstypen ($none$, $ctrl$, $low$, $mid$ und $high$)",
                         "Genotypen ($00$, $AA$, $AB$ und $BB$)"),
           tier = c("Ernährungszusatz ($ctrl$, $fedX$, $proteinX$ und $getIt$)", 
                    "Flüssignahrung ($ctrl$, $superIn$, $compostIn$ und $flOw$)",
                    "Genotypen ($00$, $AA$, $AB$ und $BB$)",
                    "Elterlinie ($ctrl$, $Standard$, $TOP$, $Yray$, $SLOW$, und $Xray$)",
                    "Lüftungssystem ($keins$, $storm$, $tornado$ und $thunder$)",
                    "Bestandsdichte ($effizient$, $standard$, $eng$, $weit$ und $kontakt$)"))[[names(obser)]] %>% 
  sample(1)

y_val <- lst(pflanze = c("Frischegewicht [kg/ha]",
                         "Trockengewicht [kg/ha]",
                         "Chlorophyllgehalt (SPAD-502Plus) [SPAD]",
                         "Proteingehalt [g/kg]"),
             tier = c("Schlachtgewicht [kg]", 
                      "Protein/Fettrate [\\%/kg]",
                      "Fettgehalt [\\%/kg]",
                      "Gewichtszuwachs in der 1LW"))[[names(obser)]] %>% 
  sample(1)

groups_vec <- x_val %>% 
  str_split("\\(|\\s|,|\\)", simplify = TRUE) %>% 
  str_subset("\\$") %>% 
  str_replace_all("\\$", "")
gen_data <- function(...){
  n_vec <- c(4:8) %>% sample(1)
  mean_vec <- c(5, 10, 12, 15, 20) %>% sample(1)
  sd_vec <- c(2, 3, 4) %>% sample(1)
  temp_tbl <- tibble(temp = rnorm(n = n_vec, mean = mean_vec, sd = sd_vec)) %>%
    mutate(temp = round(temp, 1)) %>% 
    set_names(stringi::stri_rand_strings(1, 7, '[A-Z]')) %>% 
    gather 
  return(temp_tbl)
}

ques_vec <-  c("foo") |> 
  sample(1)

@ 

\Sexpr{ques_vec}

<<multcomp-03-a, echo = FALSE>>=

data_tbl <- map_dfr(1:length(groups_vec), gen_data) %>% 
  set_names(c("treatment", "freshmatter")) %>% 
  select(treatment, freshmatter) |> 
  mutate(treatment = factor(treatment, labels = groups_vec)) %>% 
  sample_n(size = nrow(.)) 

pacman::p_load(rcompanion, magrittr, multcompView)
cld_vec <- pairwise.t.test(data_tbl$freshmatter, data_tbl$treatment,
                p.adjust.method = "none") %>% 
  extract2("p.value") %>% 
  fullPTable() %>%
  multcompLetters()

cld_vec$Letters |> 
  enframe(name = "Behandlung", value = "Compact letter display") |> 
  kable(booktabs = TRUE, align = "c") %>% 
  kable_styling(latex_options = "hold_position", font_size = 12)

@

Leider kennen sich \Sexpr{name} und \Sexpr{name_sec[1]} mit dem \textit{Compact letter display (CLD)} überhaupt nicht aus. Deshalb brauchen bei der Erstellung Ihre Hilfe!

\begin{enumerate}
  \item Formulieren Sie die wissenschaftliche Fragestellung! \textbf{(1 Punkt)}
  \item Formulieren Sie die statistischen Hypothesen! \textbf{(1 Punkt)}
\item Zeichnen Sie die sich anhand des \textit{Compact letter display (CLD)} ergebenden Barplots! \textbf{(2 Punkte)}
\item Ergänzen Sie das \textit{Compact letter display (CLD)} zu den Barplots! \textbf{(1 Punkt)}
\item Erklären Sie \textit{einen} Vorteil und \textit{einen} Nachteil des \textit{Compact letter display (CLD)}! \textbf{(2 Punkte)}
\item Erstellen Sie eine Matrix mit den paarweisen $p$-Werten eines Student t-Tests, die sich näherungsweise aus dem \textit{Compact letter display (CLD)} ergeben würde! Begründen Sie Ihre Antwort! \textbf{(3 Punkte)}
\end{enumerate}


