\section{Aufgabe \hfill (10 Punkte)}

\textit{Geben Sie grundsätzlich Formeln und Rechenweg zur Lösung der Teilaufgaben mit an!} \\[1Ex]
 
<<>>=
name <- par_lst$naming |> sample(1)
avatar_file <- list.files(file.path(exam_path, "avatare"), full.names = TRUE)|> 
  str_subset(name)
jahr <- par_lst$year
obser <- par_lst$obser |> sample(1) |> magrittr::extract2(1) |> sample(1)
avatar1file <- str_c("\\includegraphics[width = 1.3cm]{", avatar_file, "}")
@
 
%% --------------------------------------------------------------------
\begin{minipage}[t]{0.5\textwidth}
\Sexpr{avatar1file}
\end{minipage}
\begin{minipage}[t]{0.5\textwidth}
\hfill
\href{https://youtu.be/xq29O8qDrg0}{\includegraphics[width = 2cm]{img/youtube}}
\end{minipage}
\vspace{-3ex}
%% --------------------------------------------------------------------

<<>>=
pronom <- lst(sie = c("ihrem", "ihrer", "ihren", "ihr", "sie", "ihre", "ihr", "die", "Frau"),
              er = c("seinem", "seiner", "seinen", "ihm", "ihn", "seine", "sein", "der", "Mann"))[[names(name)]]
project <- c(str_c(pronom[2], " Abschlussarbeit"), str_c(pronom[1], " Projektbericht"),
             str_c(pronom[2], " Hausarbeit")) |> sample(1)
betreuer <- c(str_c(pronom[2], " Betreuerin"), str_c(pronom[1], " Betreuer")) |> sample(1)

exp <- lst(pflanze = c("ein Gewächshausexperiment",
                       "ein Freilandversuch",
                       "einen Versuch in einer Klimakammer",
                       "ein Feldexperiment"),
           tier = c("ein Stallexperiment", 
                    "ein Kreuzungsexperiment",
                    "einen Leistungssteigerungsversuch"))[[names(obser)]] %>% 
  sample(1)

x_val <- lst(pflanze = c("Düngestufen ($ctrl$, $low$, $mid$ und $high$)",
                         "Lichtstufen ($none$, $200lm$, $400lm$, $600lm$, $700lm$ und $800lm$)",
                         "Lüftungssysteme ($ctrl$, $storm$, $thunder$ und $tornado$)",
                         "Substrattypen ($kompost$, $torf$, $40p60n$, $30p20n$ und $70p30n$)",
                         "Bewässerungstypen ($none$, $ctrl$, $low$, $mid$ und $high$)",
                         "Genotypen ($00$, $AA$, $AB$ und $BB$)"),
           tier = c("Ernährungszusatz ($ctrl$, $fedX$, $proteinX$ und $getIt$)", 
                    "Flüssignahrung ($ctrl$, $superIn$, $compostIn$ und $flOw$)",
                    "Genotypen ($00$, $AA$, $AB$ und $BB$)",
                    "Elterlinie ($ctrl$, $Standard$, $TOP$, $Yray$, $SLOW$, und $Xray$)",
                    "Lüftungssystem ($keins$, $storm$, $tornado$ und $thunder$)",
                    "Bestandsdichte ($effizient$, $standard$, $eng$, $weit$ und $kontakt$)"))[[names(obser)]] %>% 
  sample(1)

y_val <- lst(pflanze = c("Frischegewicht [kg/ha]",
                         "Trockengewicht [kg/ha]",
                         "Chlorophyllgehalt (SPAD-502Plus) [SPAD]",
                         "Proteingehalt [g/kg]"),
             tier = c("Schlachtgewicht [kg]", 
                      "Protein/Fettrate [\\%/kg]",
                      "Fettgehalt [\\%/kg]",
                      "Gewichtszuwachs in der 1LW"))[[names(obser)]] %>% 
  sample(1)

groups_vec <- x_val %>% 
  str_split("\\(|\\s|,|\\)", simplify = TRUE) %>% 
  str_subset("\\$") %>% 
  str_replace_all("\\$", "")
gen_data <- function(...){
  n_vec <- c(4:8) %>% sample(1)
  mean_vec <- c(8, 10, 12, 13) %>% sample(1)
  sd_vec <- c(2, 2.5, 3) %>% sample(1)
  temp_tbl <- tibble(temp = rnorm(n = n_vec, mean = mean_vec, sd = sd_vec)) %>%
    mutate(temp = round(temp, 1)) %>% 
    set_names(stringi::stri_rand_strings(1, 7, '[A-Z]')) %>% 
    gather 
  return(temp_tbl)
}

ques_vec <-  c(str_c(name, " sitzt schon etwas länger bei ", betreuer, ". So langsam macht ", name, " sich Gedanken, ob ", names(name), " nicht doch mal anmerken sollte, dass ", names(name), " von CLD noch nie was gehört hat. Aber noch kann gelauscht werden, ein Ende ist erstmal nicht in Sicht! ", name, " hatte in ", project, " ", exp, " durchgeführt. Deshalb sitzt ", names(name), " hier. Also eigentlich nein, deshalb nicht. ", name, " will fertig werden. Hat ", names(name), " sich doch mit ", x_val, " und ", y_val, " schon eine Menge angeschaut. ", name, " beugt sich leicht nach vorne. Nein, doch keine Pause. Weiter warten auf eine Lücke im Fluss..."),
               str_c(name, " hatte in ", project, " ", exp, " durchgeführt. Soweit so gut. Dabei hat ", names(name), " sich mit ", obser, " beschäftigt. Angeblich der neueste heiße Kram... aber das ist wiederum was anderes. So richtig mitgenommen hat ", name, " das Thema dann doch nicht. Hat ", names(name), " sich doch mit ", x_val, " und ", y_val, " schon eine Menge an Daten angeschaut. Nach ", betreuer, " soll ", names(name), " nun ein CLD bestimmen. Weder weiß ", names(name), " was ein CLD ist, noch war ", pronom[7], " erster Gedanke mit Köln und die LGBTQ Community richtig..."),
               str_c(name, " betrachtet in sich gekehrt die Poster vor dem Büro von ", betreuer, ". Viele der explorativen Abbildungen sagen ", pronom[4], " etwas. Die Barplots und die Boxplots könnte ", names(name), " dann schon nachbauen. Das macht ", pronom[5], " dann zuversichtlich die Abschlussarbeit auch hinzukriegen. Etwas komischer sind die seltsamen Buchstaben über den Barplots. ", name, " betrachtet ein Poster das sich mit ", obser, " beschäftigt. ", x_val, " und ", y_val, " wurden dort bestimmt. So richtig schlau, wird ", names(name), " daraus nicht.")) |> 
  sample(1)



@ 

\paragraph{Visualisierung des Compact Letter Displays (CLD)}

\Sexpr{ques_vec}

<<multcomp-03-a, echo = FALSE>>=

data_tbl <- map_dfr(1:length(groups_vec), gen_data) %>% 
  set_names(c("treatment", "freshmatter")) %>% 
  select(treatment, freshmatter) |> 
  mutate(treatment = factor(treatment, labels = groups_vec)) %>% 
  sample_n(size = nrow(.)) 

pacman::p_load(rcompanion, magrittr, multcompView)
cld_vec <- pairwise.t.test(data_tbl$freshmatter, data_tbl$treatment,
                p.adjust.method = "none") %>% 
  extract2("p.value") %>% 
  fullPTable() %>%
  multcompLetters()

cld_vec$Letters |> 
  enframe(name = "Behandlung", value = "Compact letter display") |> 
  kable(booktabs = TRUE, align = "c") %>% 
      row_spec(0,bold=TRUE) |> 
  kable_styling(latex_options = "hold_position", font_size = 10)

@

Leider kennen sich \Sexpr{name} mit dem \textit{Compact letter display (CLD)} überhaupt nicht aus. Deshalb braucht \Sexpr{names(name)} bei der Erstellung Ihre Hilfe!

\begin{enumerate}
  \item Formulieren Sie die wissenschaftliche Fragestellung! \textbf{(1 Punkt)}
  \item Formulieren Sie die statistischen Hypothesen! \textbf{(1 Punkt)}
\item Zeichnen Sie die sich anhand des \textit{Compact letter display (CLD)} ergebenden Barplots! \textbf{(2 Punkte)}
\item Ergänzen Sie das \textit{Compact letter display (CLD)} zu den Barplots! \textbf{(1 Punkt)}
\item Erklären Sie \textit{einen} Vorteil und \textit{einen} Nachteil des \textit{Compact letter display (CLD)}! \textbf{(2 Punkte)}
\item Erstellen Sie eine Matrix mit den paarweisen $p$-Werten eines Student t-Tests, die sich näherungsweise aus dem \textit{Compact letter display (CLD)} ergeben würde! Begründen Sie Ihre Antwort! \textbf{(3 Punkte)}
\end{enumerate}


