\section{Aufgabe \hfill (12 Punkte)}

\textit{Geben Sie grundsätzlich Formeln und Rechenweg zur Lösung der Teilaufgaben mit an!} \\[1Ex]
 
<<>>=
name <- par_lst$naming |> sample(1)
name_sec <- str_subset(par_lst$naming, name, negate = TRUE) |> sample(1)
avatar_file <- list.files(file.path(exam_path, "avatare"), full.names = TRUE) |> 
  str_subset(str_c(name, name_sec, sep = "|"))
jahr <- par_lst$year
obser <- par_lst$obser
avatar1file <- str_c("\\includegraphics[width = 1.3cm]{", avatar_file[1], "}")
avatar2file <- str_c("\\includegraphics[width = 1.3cm]{", avatar_file[2], "}")
@
 
%% --------------------------------------------------------------------
\begin{minipage}[t]{0.5\textwidth}
\Sexpr{avatar1file}\hspace{-4mm}\Sexpr{avatar2file}
\end{minipage}
\begin{minipage}[t]{0.5\textwidth}
\hfill
\href{https://youtu.be/kHmfEmU6lrk}{\includegraphics[width = 2cm]{img/youtube}}
\end{minipage}
\vspace{1ex}
%% --------------------------------------------------------------------

<<>>=
pronom <- lst(sie = c("ihrem", "ihrer", "ihren", "ihr", "sie", "ihre", "ihr", "die", "Frau"),
              er = c("seinem", "seiner", "seinen", "ihm", "ihn", "seine", "sein", "der", "Mann"))[[names(name)]]
project <- c(str_c(pronom[6], " Abschlussarbeit"), str_c(pronom[8], " Projektbericht"),
             str_c(pronom[6], " Hausarbeit")) |> sample(1)
betreuer <- c(str_c(pronom[6], " Betreuerin"), str_c(pronom[7], " Betreuer")) |> sample(1)

exp <- lst(pflanze = c("ein Gewächshausexperiment",
                       "ein Freilandversuch",
                       "einen Versuch in einer Klimakammer",
                       "ein Feldexperiment"),
           tier = c("ein Stallexperiment", 
                    "ein Kreuzungsexperiment",
                    "einen Leistungssteigerungsversuch"))[[names(obser)]] %>% 
  sample(1)

study <- c("Almar et al. (2012)", "Totsdorf et al. (2018)", "Meyer et al. (2021)", "Qui et al. (2017)") |> 
  sample(1)

stoerung <- c("Krähen", "Würmer", "Hunde", "Katzen", "Wölfe") |> sample(1)

x_val <- lst(pflanze = c("Düngestufen ($ctrl$, $low$, $mid$ und $high$)",
                         "Lichtstufen ($none$, $200lm$, $400lm$, $600lm$, $700lm$ und $800lm$)",
                         "Lüftungssysteme ($ctrl$, $storm$, $thunder$ und $tornado$)",
                         "Substrattypen ($kompost$, $torf$, $40p60n$, $30p20n$ und $70p30n$)",
                         "Bewässerungstypen ($none$, $ctrl$, $low$, $mid$ und $high$)",
                         "Genotypen ($00$, $AA$, $AB$ und $BB$)"),
           tier = c("Ernährungszusatz ($ctrl$, $fedX$, $proteinX$ und $getIt$)", 
                    "Flüssignahrung ($ctrl$, $superIn$, $compostIn$ und $flOw$)",
                    "Genotypen ($00$, $AA$, $AB$ und $BB$)",
                    "Elterlinie ($ctrl$, $Standard$, $TOP$, $Yray$, $SLOW$, und $Xray$)",
                    "Lüftungssystem ($keins$, $storm$, $tornado$ und $thunder$)",
                    "Bestandsdichte ($effizient$, $standard$, $eng$, $weit$ und $kontakt$)"))[[names(obser)]] %>% 
  sample(1)

y_val <- lst(pflanze = c("Frischegewicht [kg/ha]",
                         "Trockengewicht [kg/ha]",
                         "Chlorophyllgehalt (SPAD-502Plus) [SPAD]",
                         "Proteingehalt [g/kg]"),
             tier = c("Schlachtgewicht [kg]", 
                      "Protein/Fettrate [\\%/kg]",
                      "Fettgehalt [\\%/kg]",
                      "Gewichtszuwachs in der 1LW"))[[names(obser)]] %>% 
  sample(1)

groups_vec <- x_val %>% 
  str_split("\\(|\\s|,|\\)", simplify = TRUE) %>% 
  str_subset("\\$") %>% 
  str_replace_all("\\$", "")

ques_vec <-  c(str_c("In ", exp, " mit ", obser, " wurde die Behandlung ", x_val, " gegen die Ergebnisse einer früheren Studie von ", study, " verglichen. Im Rahmen des Experiments haben ", name, " und ", name_sec, " verschiedene Student t-Tests für den Mittelwertsvergleich für den Messwert ", y_val, " gerechnet. Es ergab sich dann die folgende Tabelle der rohen p-Werte für die Vergleiche zu ", study, ". Jetzt sollen die beiden einmal schauen, was in den Daten so drin ist."),
               str_c("'Moment, die haben ja das Gleiche gemacht wie wir!', ruft ", name, " laut aus. ", name_sec, " schaut etwas verwundert. 'Das glaube ich eher nicht. Lass uns mal unsere Daten mit den Ergebnissen von ", study, " vergleichen.', antwortet ", name_sec, ". In ", exp, " mit ", obser, " wurde die Behandlung ", x_val, " auf den Messwert ", y_val, " untersucht. Jetzt müssen die beiden mal schauen, ob sie wirklich was Neues gefunden haben oder ob die Ergebnisse alle die gleichen sind wie schon bei ", study, ". Es ergab sich dann die folgende Tabelle der rohen p-Werte für die Vergleiche zu ", study, "."),
               str_c(name, " und ", name_sec, " untersuchen gemeinsam in ihrer Abschlussarbeit den Messwert ", y_val, " in ", obser, ". Es ist einiges schiefgelaufen, wie es immer so passiert. Hauptsächlich waren es ", stoerung, ", auch wenn man erstmal bei dem Messwert nicht unbedingt an ", stoerung, " denken würde. Aber das ist eine andere Geschichte. Jetzt wollen ", name, " und ", name_sec, " ihre Ergebnisse nochmal mit einer Studie von ", study, " vergleichen und schauen, ob was ähnliches rauskommt. Angeschaut wurde sich als Behandlung ", x_val, ". Es ergab sich dann die folgende Tabelle der rohen p-Werte für die Vergleiche zu ", study, ".")
               ) |>   sample(1)

@ 

\Sexpr{ques_vec}

<<multcomp-01-a, echo = FALSE>>=

pval_vec <- c(0.001, 0.02, 0.012, 0.03,
              0.34, 0.76, 0.06, 0.08,
              0.0012, 0.23, 0.002, 0.07) %>%
  sample(length(groups_vec))

tibble(#Vergleich = str_c(groups_vec, " - [", study, "]"),
       pval = pval_vec,
       adj = c(""),
       reject = c("")) %>%
  set_names(c("Rohen p-Werte", "Adjustierte p-Werte", "Nullhypothese ablehnen?")) %>% 
  kable(booktabs = TRUE, align = "c") %>% 
      row_spec(0,bold=TRUE) |> 
  kable_styling(latex_options = "hold_position", font_size = 10)

@

Leider kennen sich \Sexpr{name} und \Sexpr{name_sec[1]} mit der Adjustierung von $p$-Werten und dem Signifikanzniveau $\alpha$ überhaupt nicht aus. Deshalb brauchen die beiden bei der Erstellung Ihre Hilfe!

\begin{enumerate}
  \item Formulieren Sie die wissenschaftliche Fragestellung! \textbf{(1 Punkt)}
  \item Formulieren Sie die statistischen Hypothesen! \textbf{(1 Punkt)}
\item Füllen Sie die Spalte \textit{Adjustierte p-Werte} nach der Bonferoni-Methode aus! \textbf{(2 Punkte)}
\item Entscheiden Sie, ob nach der Adjustierung die Nullhypothese abgelehnt werden kann! Begründen Sie Ihre Antwort! \textbf{(2 Punkte)}
\item Wie ist Ihr Vorgehen, wenn Sie anstatt der $p$-Werte das Signifikanzniveau $\alpha$ adjustieren? \textbf{(2 Punkte)}
\item Erklären Sie warum die $p$-Werte oder das Signifikanzniveau $\alpha$ bei multiplen Vergleichen adjustiert werden müssen! \textbf{(2 Punkte)}
\item Würden Sie die Adjustierung der $p$-Werte oder die Adjustierung des Signifikanzniveaus $\alpha$ vorziehen? Begründen Sie Ihre Antwort! \textbf{(2 Punkte)}
\end{enumerate}



