\section{Aufgabe \hfill (9 Punkte)}

<<>>=
name <- par_lst$naming |> sample(1)
name_sec <- str_subset(par_lst$naming, name, negate = TRUE) |> sample(1)
avatar_file <- list.files(file.path(exam_path, "avatare"), full.names = TRUE) |> 
  str_subset(str_c(name, name_sec, sep = "|"))
jahr <- par_lst$year
obser <- par_lst$obser |> sample(1) |> magrittr::extract2(1) |> sample(1)
avatar1file <- str_c("\\includegraphics[width = 1.3cm]{", avatar_file[1], "}")
avatar2file <- str_c("\\includegraphics[width = 1.3cm]{", avatar_file[2], "}")
@
 
%% --------------------------------------------------------------------
\ifcollection
\begin{flushright}
\tiny
\textbf{\examinhaltstart}
\exammodulestat $\;\bullet$
\exammodulestatbbv $\;\bullet$
\exammodulestatversuch $\;\bullet$
\exammodulebiostat
\vspace{-4Ex}
\end{flushright}
\begin{minipage}[t]{0.5\textwidth}
\Sexpr{avatar1file}\hspace{-4mm}\Sexpr{avatar2file}
\end{minipage}
\begin{minipage}[t]{0.5\textwidth}
\hfill
\href{https://youtu.be/Ric8ne39DtI}{\includegraphics[width = 2cm]{img/youtube}}
\end{minipage}
\fi
%% --------------------------------------------------------------------

<<>>=
pronom <- lst(sie = c("ihrem", "ihrer", "ihren"),
              er = c("seinem", "seiner", "seinen"))[[names(name)]]

sentence_name_vec <- sentence_func(name, pronom, attr_lst[[name]])
attr_name_vec <- attr_lst[[name]]
attr_name_sec1_vec <- attr_lst[[name_sec[1]]]

time_vec <- sample(c("Monat", "Jahr", "halben Jahr"), 1)
words <- c("(Unbekannte) Wahrheit", "H$_0$ wahr", "H$_0$ falsch",
           "H$_0$ abgelehnt", "H$_0$ beibehalten", "Testentscheidung",
           "$\\alpha$-Fehler", "$\\beta$-Fehler", "Richtige Entscheidung",
           "5\\%", "20\\%") %>% sample(4)

footnote_str <- c("\\footnote{Yang, P. J., et al. (2014). Duration of urination does not change with body size. Proceedings of the National Academy of Sciences, 111(33), 11932-11937.}")

ques_vec <-  c(str_c("'", str_replace(attr_name_vec$sport, "zu ", ""), " ist der beste Sport, den es gibt.', meint ", name, ". ", name_sec, " entgegnet, ' Ich empfehle ja immer allen ", str_replace(attr_name_sec1_vec$sport, "zu ", ""), ".' Die beiden sind im Zoo und diskutieren, ob Pinguine Knie haben. Eigentlich wollten beide nochmal die statistische Testheorie durchgehen, sind dann aber auf abenteuerlichen Wege im Zoo gelandet. ", name, " starrt wie hypnotisiert auf einen strullenden Elefanten und stopt die Zeit.", footnote_str, " 'Du bist so peinlich.', entfährt es ", name_sec, "."),
               str_c("'", attr_name_vec$film, " ist der beste Film, den es gibt.', meint ", name, ". ", name_sec, " entgegnet, ' Ich empfehle ja immer allen ", attr_name_sec1_vec$film, ".'Die beiden sind im Zoo und diskutieren, ob Pinguine Knie haben. Eigentlich wollten beide nochmal die statistische Testheorie durchgehen, sind dann aber auf abenteuerlichen Wege im Zoo gelandet. ", name, " starrt wie hypnotisiert auf einen strullenden Elefanten und stopt die Zeit.", footnote_str, " 'Du bist so peinlich.', entfährt es ", name_sec, " und schmeißt sich noch ein paar überteuerte ", attr_name_sec1_vec$sweet, " rein."),
               str_c("'Das Känguruh hat mir gerade zugezwinkert. Das macht mir Angst', bemerkt ", name, ". Es reicht ja schon ein Problem. ", sentence_name_vec$flaw, " Da braucht es nicht noch Wahnvorstellungen. 'Ich glaube nicht, das Känguruhs zwinkern. Aber was Wichtigeres. Wo hast du eigentlich meine Schnapspralinen hingetan? Wir haben nur noch ", attr_name_vec$sweet, " von dir. Bäh!', antwortet ", name_sec, ". Beide sind im Zoo und wollen sich von der statistische Testheorie ablenken lassen. Eigentlich wollte ja ", name, " stoppen wie lange Tiere pinkeln", footnote_str, ", scheiterte aber an einer Oma mit Stock, die die beiden beschimpfte.")) |> 
  sample(1)




@ 

\ifcollection
\paragraph{Das Nullritual - Die statistische Testtheorie}
\fi

\Sexpr{ques_vec}

\vspace{1ex}

Leider kennen sich \Sexpr{name} und \Sexpr{name_sec} mit statistischen Testtheorie, auch Null-Ritual genannt, überhaupt nicht aus. Geschweige denn mit der Visualisierung als Kreuztabelle.  

\begin{enumerate}
\item Tragen Sie folgende statistische Fachbegriffe zur statistischen Testtheorie korrekt eine selbst erstellte Kreuztabelle ein! \textbf{(3 Punkte)}
  \begin{center}
  \begin{tabular}{cccc}
  \Sexpr{words[1]} & \Sexpr{words[2]} & \Sexpr{words[3]} & \Sexpr{words[4]} \\
  \end{tabular}
  \end{center}
\item Ergänzen Sie Ihre erstellte Kreuztabelle um vier weitere, passende Fachbegriffe zur statistischen Testtheorie! \textbf{(2 Punkte)}
\end{enumerate}

Die Entscheidungsfindung durch einen statistischen Test kann auch durch die Analogie zu einem Feuermelder abgebildet werden. Dabei symbolisiert der Feuermelder den statistischen Test und es soll getestet werden, ob ein Feuer ausgebrochen ist.

\begin{enumerate}
  \setcounter{enumi}{2}    
\item In der Analogie des Feuermelders, wie lautet der $\alpha$-Fehler? \textbf{(1 Punkt)}
\item In der Analogie des Feuermelders, wie lautet der $\beta$-Fehler? \textbf{(1 Punkt)}
\item Wenn der Feuermelder einmal pro Tag messen würde, wie oft würde der Feuermelder mit einem $\alpha$ von 5\% in einem \Sexpr{time_vec} Alarm schlagen? Begründen Sie Ihre Antwort! \textbf{(2 Punkte)}
\end{enumerate}




