\section{Aufgabe \hfill (9 Punkte)}

\textit{Geben Sie grundsätzlich Formeln und Rechenweg zur Lösung der Teilaufgaben mit an!} \\[1Ex]

<<>>=
name <- par_lst$naming |> sample(1)
name_sec <- str_subset(par_lst$naming, name, negate = TRUE) |> sample(1)
avatar_file <- list.files(file.path(exam_path, "avatare"), full.names = TRUE) |> 
  str_subset(str_c(name, name_sec, sep = "|"))
jahr <- par_lst$year
obser <- par_lst$obser |> sample(1) |> magrittr::extract2(1) |> sample(1)
avatar1file <- str_c("\\includegraphics[width = 1.3cm]{", avatar_file[1], "}")
avatar2file <- str_c("\\includegraphics[width = 1.3cm]{", avatar_file[2], "}")
@
 
%% --------------------------------------------------------------------
\ifcollection
\begin{flushright}
\tiny\vspace{-3Ex}
\textbf{\examinhaltstart}
\exammodulemathstat $\;\bullet$
\exammodulestat $\;\bullet$
\exammodulestatbbv $\;\bullet$
\exammodulestatversuch $\;\bullet$
\exammodulebiostat
\vspace{-4Ex}
\end{flushright}
\begin{minipage}[t]{0.5\textwidth}
\Sexpr{avatar1file}\hspace{-4mm}\Sexpr{avatar2file}
\end{minipage}
\begin{minipage}[t]{0.5\textwidth}
\hfill
\href{https://youtu.be/2LQzyQCy2FI}{\includegraphics[width = 2cm]{img/youtube}}
\end{minipage}
\fi
%% --------------------------------------------------------------------

<<>>=
pronom <- lst(sie = c("ihrem", "ihrer", "ihren", "ihr", "sie", "ihre", "ihr", "die", "Frau"),
              er = c("seinem", "seiner", "seinen", "ihm", "ihn", "seine", "sein", "der", "Mann"))[[names(name)]]

sentence_name_vec <- sentence_func(name, pronom, attr_lst[[name]])
attr_name_vec <- attr_lst[[name]]
attr_name_sec1_vec <- attr_lst[[name_sec[1]]]

sig_vec <- c("signifikant", "nicht signifikant") %>%
  sample(1)
sign_vec  <- c("+", "-") %>%
  sample(1)
a_vec <- c("A = 0.95", "A = 95\\%", "95\\%") %>% sample(1)

ques_vec <-  c(str_c("'Wir sollen die Teststatistik $T_D$ umd dem p-Wert visualisieren, da mit einer Visualisierung vieles verständlicher wird!', ruft ", name, " um ", attr_name_vec$music, " zu übertönen. 'Ich weiß nicht, was das jetzt helfen soll. Können wir nicht einfach schauen, ob der p-Wert kleiner als das Signifikanzniveau  $\\alpha$ gleich 5\\% ist? Und gut ist?', merkt ", name_sec, " an, was aber im Refrain von ", attr_name_vec$music, " untergeht. ", name, " nickt im Beat. 'Wir haben hier eine t-verteilung unter der Annahme der Nullhypothese!', singt ", names(name), "."),
               str_c("'Kannst du mir nochmal an einer Visualisierung erklären, wie der Zusammenhang zwischen der Teststatistik aus den Daten $T_D$ und dem p-Wert ist? Ich habe hier zig Fachbegriffe, kriege die abr nicht zusammen...', fragt ", name, " nachdrücklich  ", name_sec, ". Das hilft aber nur bedingt, denn ", name_sec, " hat wenig geschlafen und träumt zu den Klängen von ", attr_name_vec$music, ". ", name, " hatte den ganzen Abend mit ", name_sec, " über ", attr_name_vec$flaw, " diskutiert und nun sind beide voll neben der Spur. So wird es nichts mit der Klausur. ", name, " mampft noch ein paar ", attr_name_vec$sweet, " und nickt ein. Jetzt brauchen die beiden gesondert Hilfe!"),
               str_c(name, " und ", name_sec, " wollten eigentlich einen Flug nach Mallorca buchen, sind jetzt aber dann doch dazu übergegangen nochmal die Aufgaben für die Statistikklausur durchzugehen. 'Kannst du mir nochmal an einer Visualisierung erklären, wie der Zusammenhang zwischen der Teststatistik aus den Daten $T_D$ und dem p-Wert ist? Ich habe hier zig Fachbegriffe, kriege die abr nicht zusammen...', fragt ", name, ". ", name_sec, " zuckt mit den Schultern. So genau hatte ", name_sec, " jetzt auch nicht aufgepasst. Da hilft dann eventuell das YouTube Video weiter. ", name, " mapmft ", attr_name_vec$sweet, " und fragt sich, was das alles soll.")) |> 
  sample(1)



@ 

\ifcollection
\paragraph{Visualisierung der Teststatistik $\boldsymbol{T_D}$ und dem p-Wert}
\fi

\Sexpr{ques_vec}

\vspace{1ex}

Leider kennen sich \Sexpr{name} und \Sexpr{name_sec} mit der Visualisierung der Teststatistik $T_D$ und dem p-Wert überhaupt nicht aus und brauchen dahr Ihre Hilfe!

\vspace{1ex}

\textit{Beachten Sie, dass im Folgenden \underline{keine numerisch korrekte Darstellung} verlangt wird! Es gilt Erkennbarkeit vor Genauigkeit!}

\begin{enumerate}
\item Ergänzen Sie eine beschriftete $x$-Achse! \textbf{(1 Punkt)}
\item Ergänzen Sie "`$\bar{y}_1 = \bar{y}_2$"'! \textbf{(1 Punkt)} 
\item Ergänzen Sie "`$\Sexpr{a_vec}$"'! \textbf{(1 Punkt)}
\item Zeichnen Sie $T_{\alpha=5\%}$ in die Abbildung! \textbf{(1 Punkt)} 
\item Zeichnen Sie das Signifikanzniveau $\alpha$ in die Abbildung! Begründen Sie Ihre Antwort! \textbf{(2 Punkte)} 
\item Zeichnen Sie $\Sexpr{sign_vec}T_{D}$ in die Abbildung! \textbf{(1 Punkt)}
\item Zeichnen Sie einen \Sexpr{sig_vec} p-Wert in die Abbildung! Begründen Sie Ihre Antwort! \textbf{(2 Punkte)}   
\end{enumerate}

<<statistisches-testen-3, results='asis', echo = FALSE, fig.height = 5, fig.width = 8, fig.align = "center", message = FALSE>>=

ggplot(data.frame(x = c(-5, 5)), aes(x = x)) +
  stat_function(fun = dt, args = list(df = 3)) +
  theme_minimal() +
  labs(x = "", y = "") +
  scale_x_continuous(breaks = c(-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5)) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank())

@