\section{Aufgabe \hfill (9 Punkte)}

%% --------------------------------------------------------------------
\hfill\href{https://youtu.be/32JjH1eyuTU}{\includegraphics[width =
  2cm]{img/youtube}}\\[1Ex]
%% --------------------------------------------------------------------

<<>>=

sig_vec <- c("signifikant", "nicht signifikant") %>%
  sample(1)
sign_vec  <- c("+", "-") %>%
  sample(1)

@ 

Im Folgenden ist die t-Verteilung unter der Anahme der G{\"u}ltigkeit der
Nullhypothese abgebildet. 

\begin{enumerate}
\item Erg{\"a}nzen Sie die Beschriftung der $x$-Achse! \textbf{(1 Punkt)}
\item Erg{\"a}nzen Sie "`$\bar{y}_1 = \bar{y}_2$"'! \textbf{(1 Punkt)} 
\item Erg{\"a}nzen Sie "`$A = 0.95$"'! \textbf{(1 Punkt)}
\item Zeichnen Sie $T_{\alpha=5\%}$ in die Abbildung! \textbf{(1 Punkt)} 
\item Zeichnen Sie das Signifikanzniveau $\alpha$ in die Abbildung! \textbf{(2 Punkte)} 
\item Zeichnen Sie $\Sexpr{sign_vec}T_{calc}$ in die Abbildung! \textbf{(1
    Punkt)}
\item Zeichnen Sie einen \Sexpr{sig_vec} p-Wert in die Abbildung! \textbf{(2 Punkte)}   
\end{enumerate}

<<statistisches-testen-3, results='asis', echo = FALSE, fig.height = 5, fig.width = 6, fig.align = "center", message = FALSE>>=

ggplot(data.frame(x = c(-5, 5)), aes(x = x)) +
  stat_function(fun = dt, args = list(df = 3)) +
  theme_minimal() +
  labs(x = "", y = "") +
  scale_x_continuous(breaks = c(-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5))

@