\section{Aufgabe \hfill (11 Punkte)}

\textit{Geben Sie grunds{\"a}tzlich Formeln und Rechenweg zur L{\"o}sung der
  Teilaufgaben mit an!} \\[1Ex]

%% --------------------------------------------------------------------
\hfill\href{https://youtu.be/QR90zyn0Iz8}{\includegraphics[width =
  2cm]{img/youtube}}\\[1Ex]
%% --------------------------------------------------------------------

<<>>=

jahr <- "2024"
name <- c("Jessica", "Paula", "Tina", "Sabine", "Adele",
          "Mark", "Jonas", "Eric", "Nikolas", "Manuel") |> 
  set_names(c("sie", "sie", "sie", "sie", "sie",
              "er", "er", "er", "er", "er")) |> sample(1)
pronom <- lst(sie = c("ihrem", "ihrer", "ihren", "ihr", "sie", "ihre", "ihr", "die", "Frau"),
              er = c("seinem", "seiner", "seinen", "ihm", "ihn", "seine", "sein", "der", "Mann"))[[names(name)]]
project <- c(str_c(pronom[6], " Abschlussarbeit"), str_c(pronom[3], " Projektbericht"),
             str_c(pronom[2], " Hausarbeit")) |> sample(1)
betreuer <- c(str_c(pronom[2], " Betreuerin"), str_c(pronom[1], " Betreuer")) |> sample(1)
outcome_name <- c("ein normalverteiltes Outcome ($Y$)", "einen normalverteilten Endpunkt ($Y$)", "einen normalverteilten Messwert ($Y$)") |> sample(1)
ort <- c("in der Uckermark", "im Oldenburger Land", "im Teuteburgerwald", "im Emsland", "im Wendland") |> sample(1)
ort_2 <- c("Die Uckermark", "Das Oldenburger Land", "Der Teuteburgerwald", "Das Emsland", "Das Wendland") |> sample(1)


plant <- c("Maiss", "Erbsen", "Kartoffeln", "Lauch", "Erdbeeren", "Brokoli", "Spargel") %>% 
  sample(1) |> 
  set_names("pflanze")
animal <- c("Puten", "Schweinen", "Fleischrindern", "Lamas", "Hühnern", "Zandern", "Milchvieh") |> 
  sample(1) |> 
  set_names("tier")
obser <- c(plant, animal) |> sample(1)


exp <- lst(pflanze = c("ein Gewächshausexperiment",
                       "ein Freilandversuch",
                       "einen Versuch in einer Klimakammer",
                       "ein Feldexperiment"),
           tier = c("ein Stallexperiment", 
                    "ein Kreuzungsexperiment",
                    "einen Leistungssteigerungsversuch"))[[names(obser)]] %>% 
  sample(1)

x_val <- lst(pflanze = c("Düngung ($vorher$ und $nachher$)",
                         "Beschattung ($7d$ und $14d$)",
                         "Ausgeizen ($ctrl$ und $28d$)",
                         "Jäten ($Aussaat$ und $Ernte$)"),
           tier = c("Ernährungszusatz ($ohne$ und $14d$)", 
                    "Flüssignahrung ($1l/d$ und $5l/d$)",
                    "Genotypisierung ($0d$ und $14d$)",
                    "Bestandsdichte ($hoch$ und $niedrig$)"))[[names(obser)]] %>% 
  sample(1)

y_val <- lst(pflanze = c("Frischegewicht [kg/ha]",
                         "Trockengewicht [kg/ha]",
                         "Chlorophyllgehalt (SPAD-502Plus) [SPAD]",
                         "Proteingehalt [g/kg]"),
             tier = c("Schlachtgewicht [kg]", 
                      "Protein/Fettrate [\\%/kg]",
                      "Fettgehalt [\\%/kg]",
                      "Gewichtszuwachs in der 1LW"))[[names(obser)]] %>% 
  sample(1)


groups_vec <- x_val %>% 
  str_split("\\(|\\s|,|\\)", simplify = TRUE) %>% 
  str_subset("\\$") %>% 
  str_replace_all("\\$", "")
gen_data <- function(...){
  n_vec <- c(7:11) %>% sample(1)
  mean_vec <- c(25, 30, 35, 40, 45) %>% sample(1)
  sd_vec <- c(4, 6, 8, 10) %>% sample(1)
  temp_tbl <- tibble(temp = rnorm(n = n_vec, mean = mean_vec, sd = sd_vec)) %>%
    mutate(temp = round(temp, 1)) %>% 
    set_names(stringi::stri_rand_strings(1, 7, '[A-Z]')) %>% 
    gather |> 
    mutate(ID = 1:n_vec)
  return(temp_tbl)
}
ques_vec <- c("foo") |> 
  sample(1)

ques_vec <- c("foo")

@

\Sexpr{ques_vec}

Das Schlachtgewicht von wölfen h{\"a}ngt ma{\ss}geblich von der
Gewichtszunahme in den ersten sieben Tagen hab. Um einen F{\"u}tterungsversuch
in verschiedenen St{\"a}llen zu planen w{\"u}rde ein Pilotversuch durchgef{\"u}hrt. Das
Gewicht von wölfen wurde \textit{vor} der Behandlung mit
xxx und 1 Woche \textit{nach} der Behandlung gemessen. Es ergibt
sich die folgende Datentabelle.

<<ttest-02, results='asis', echo = FALSE>>=
t_crit <- c(2.04, 1.96, 1.84, 1.64, 2.68) %>% sample(1)

data_tbl <- map_dfr(1:length(groups_vec), gen_data) %>% 
  set_names(c("treatment", "freshmatter", "ID")) %>% 
  select(ID, treatment, freshmatter) |> 
  mutate(treatment = factor(treatment, labels = groups_vec)) %>% 
  sample_n(size = nrow(.)) 

data_tbl |> 
  kable(booktabs = TRUE, align = "c") %>% 
  kable_styling(latex_options = "hold_position")
@

Leider kennt sich \Sexpr{name} mit der Berechnung eines gepaarten t-Tests überhaupt nicht aus. Deshalb braucht \Sexpr{names(name)} bei der Berechnung Ihre Hilfe!

\begin{enumerate}
  \item Formulieren Sie die wissenschaftliche Fragestellung! \textbf{(1 Punkt)}
  \item Formulieren Sie das statistische Hypothesenpaar! \textbf{(1 Punkt)}
  \item Bestimmen Sie die Teststatistik $T_{D}$ eines gepaarten t-Tests! \textbf{(3 Punkte)}
  \item Treffen Sie mit $T_{\alpha = 5\%} = \Sexpr{t_crit}$ eine Aussage zur Nullhypothese! Begründen Sie Ihre Antwort! \textbf{(2 Punkte)}
\item Schätzen Sie den $p$-Wert des gepaarten t-Tests ab! Begründen Sie Ihre Antwort mit einer Skizze! \textbf{(2 Punkte)}
\item Formulieren Sie eine Antwort an \Sexpr{name} über das Ergebnis Ihrer statistischen Analyse! \textbf{(2 Punkte)}
\end{enumerate}



