\section{Aufgabe \hfill (12 Punkte)}

\textit{Geben Sie grundsätzlich Formeln und Rechenweg zur L{\"o}sung der
  Teilaufgaben mit an!} \\[1Ex]

%% --------------------------------------------------------------------
\hfill\href{https://youtu.be/Cq_rF_z4xOk}{\includegraphics[width =
  2cm]{img/youtube}}\\[1Ex]
%% --------------------------------------------------------------------

<<>>=

name <- c("Jessica", "Paula", "Tina", "Sabine", "Adele",
          "Mark", "Noa", "Eric", "Nikolas", "Manuel") |> 
  set_names(c("sie", "sie", "sie", "sie", "sie",
              "er", "er", "er", "er", "er")) |> sample(1)
pronom <- lst(sie = c("ihrem", "ihrer", "ihren", "ihr", "sie", "ihre", "ihr"),
              er = c("seinem", "seiner", "seinen", "ihm", "ihn", "seine", "sein"))[[names(name)]]
project <- c(str_c(pronom[2], " Abschlussarbeit"), str_c(pronom[2], " Projektbericht"),
             str_c(pronom[2], " Hausarbeit")) |> sample(1)
betreuer <- c(str_c(pronom[6], " Betreuerin"), str_c(pronom[7], " Betreuer")) |> sample(1)
outcome_name <- c("Outcome ($Y$)", "Endpunkt ($Y$)", "Messwert ($Y$)") |> sample(1)
ort <- c("in der Uckermark", "im Oldenburger Land", "im Teuteburgerwald", "im Emsland", "im Wendland") |> sample(1)

plant <- c("Maiss", "Erbsen", "Kartoffeln", "Lauch", "Erdbeeren", "Brokoli", "Spargel") %>% 
  sample(1) |> 
  set_names("pflanze")
animal <- c("Puten", "Schweinen", "Fleischrindern", "Lamas", "Hühnern", "Zandern", "Milchvieh") |> 
  sample(1) |> 
  set_names("tier")
obser <- c(plant, animal) |> sample(1)


exp <- lst(pflanze = c("ein Gewächshausexperiment",
                       "ein Freilandversuch",
                       "einen Versuch in einer Klimakammer",
                       "ein Feldexperiment"),
           tier = c("ein Stallexperiment", 
                    "ein Kreuzungsexperiment",
                    "einen Leistungssteigerungsversuch"))[[names(obser)]] %>% 
  sample(1)

x_val <- lst(pflanze = c("Düngestufen ($ctrl$ und $high$)",
                       "Lichtstufen ($none$ und $600lm$)",
                       "Lüftungssystemen und Folientunneln ($ctrl$ und $tornado$)",
                       "Substrattypen ($torf$ und $70p30n$)",
                       "Bewässerungstypen ($low$ und $high$)",
                       "Genotypen ($AA$ und $BB$)"),
           tier = c("Ernährungszusatz ($ctrl$ und $fedX$)", 
                    "Flüssignahrung ($ctrl$ und $flOw$)",
                    "Genotypen ($AA$ und $BB$)",
                    "Elterlinie ($Standard$ und $Xray$)",
                    "Lüftungssystem ($keins$ und $vorhanden$)",
                    "Bestandsdichte ($Verordnung$ und $Leicht erhöht$)"))[[names(obser)]] %>% 
  sample(1)

y_val <- lst(pflanze = c("Frischegewicht [kg/ha]",
                         "Trockengewicht [kg/ha]",
                         "Chlorophyllgehalt (SPAD-502Plus) [SPAD]",
                         "Proteingehalt [g/kg]"),
             tier = c("Schlachtgewicht [kg]", 
                      "Protein/Fettrate [\\%/kg]",
                      "Fettgehalt [\\%/kg]",
                      "Gewichtszuwachs in der 1LW"))[[names(obser)]] %>% 
  sample(1)


groups_vec <- x_val %>% 
  str_split("\\(|\\s|,|\\)", simplify = TRUE) %>% 
  str_subset("\\$") %>% 
  str_replace_all("\\$", "")
gen_data <- function(...){
  n_vec <- c(7:11) %>% sample(1)
  mean_vec <- c(25, 30, 35, 40, 45) %>% sample(1)
  sd_vec <- c(4, 6, 8, 10) %>% sample(1)
  temp_tbl <- tibble(temp = rnorm(n = n_vec, mean = mean_vec, sd = sd_vec)) %>%
    mutate(temp = round(temp, 1)) %>% 
    set_names(stringi::stri_rand_strings(1, 7, '[A-Z]')) %>% 
    gather
  return(temp_tbl)
}
ques_vec <- c("foo") |> 
  sample(1)

effect_test <- c("die Teststatistik $T_{D}$", "der Effekt") |> sample(1)

str_c("Der t-Test. ", name, " erschaudert. Ein mächtiges Werkzeug in den Händen desjenigen, der ein normalverteiltes ", outcome_name, " hat. Aber erstmal überhaupt rechnen können. ", name, " hat ", exp, " mit ", obser, " durchgeführt. Dabei wurde die Behandlung ", x_val, " an den ", obser, " getestet. Gemessen hat ", name, " dann als Messwert ", y_val, ".")

@ 

\Sexpr{ques_vec}

<<ttest-01, results='asis', echo = FALSE>>=

x_val <- str_replace(x_val, "\\\\", "")
y_val <- str_replace(y_val, "\\\\", "")

data_tbl <- map_dfr(1:length(groups_vec), gen_data) %>% 
  set_names(c("treatment", "freshmatter")) %>%
  mutate(treatment = factor(treatment, labels = groups_vec)) %>% 
  sample_n(size = nrow(.)) 

t_calc <- t.test(freshmatter ~ treatment, data_tbl)$statistic

t_crit <- c(2.04, 1.96, 1.84, 1.64, 2.68) %>% sample(1)

if(t_calc >= 2.04){
  textsig <- "keinen"
} else {
  textsig <- "einen"
}

x_val <- x_val |> str_split(" ", simplify = TRUE) |> magrittr::extract(1,1)
y_val <- y_val |> str_split(" ", simplify = TRUE) |> magrittr::extract(1,1)

data_tbl %>% 
  set_names(c(x_val, y_val)) |> 
  kable(booktabs = TRUE, align = "c") %>% 
  kable_styling(latex_options = "hold_position")
@

Leider kennt sich \Sexpr{name} mit der Berechnung eines t-Tests überhaupt nicht aus. Deshalb braucht \Sexpr{names(name)} bei der Berechnung Ihre Hilfe!

\begin{enumerate}
  \item Formulieren Sie die wissenschaftliche Fragestellung! \textbf{(1 Punkt)}
  \item Formulieren Sie das statistische Hypothesenpaar! \textbf{(2 Punkte)}
  \item Bestimmen Sie die Teststatistik $T_{D}$ eines Student t-Tests! \textbf{(4 Punkte)}
\item Treffen Sie mit $T_{\alpha = 5\%} = \Sexpr{t_crit}$ eine Aussage zur Nullhypothese! Begründen Sie Ihre Antwort! \textbf{(2 Punkte)}
\item Berechnen Sie den Effekt des Student t-Tests! \textbf{(1 Punkt)}
\item Wenn Sie \textit{\Sexpr{textsig}} Unterschied zwischen den Behandlungsgruppen erwarten würden, wie groß wäre dann \Sexpr{effect_test}? Begründen Sie Ihre Antwort! \textbf{(2 Punkte)}
\end{enumerate}
