\section{Aufgabe \hfill (9 Punkte)}

\textit{Geben Sie grundsätzlich Formeln und Rechenweg zur Lösung der Teilaufgaben mit an!} \\[1Ex]
 
<<>>=
name <- par_lst$naming |> sample(1)
avatar_file <- list.files(file.path(exam_path, "avatare"), full.names = TRUE)|> 
  str_subset(name)
jahr <- par_lst$year
obser <- par_lst$obser |> sample(1) |> magrittr::extract2(1) |> sample(1)
avatar1file <- str_c("\\includegraphics[width = 1.3cm]{", avatar_file, "}")
@
 
%% --------------------------------------------------------------------
\begin{minipage}[t]{0.5\textwidth}
\Sexpr{avatar1file}
\end{minipage}
\begin{minipage}[t]{0.5\textwidth}
\hfill
\href{https://youtu.be/eejS2uG4o-M}{\includegraphics[width = 2cm]{img/youtube}}
\end{minipage}
\vspace{-3ex}
%% --------------------------------------------------------------------

<<>>=

pronom <- lst(sie = c("ihrem", "ihrer", "ihren", "ihr", 
                      "sie", "ihre", "ihr", "die", "Frau"),
              er = c("seinem", "seiner", "seinen", "ihm", 
                     "ihn", "seine", "sein", "der", "Mann"))[[names(name)]]
project <- c(str_c(pronom[6], " Abschlussarbeit"), str_c(pronom[3], " Projektbericht"),
             str_c(pronom[2], " Hausarbeit")) |> sample(1)
betreuer <- c(str_c(pronom[2], " Betreuerin"), str_c(pronom[1], " Betreuer")) |> sample(1)
outcome_name <- c("ein normalverteiltes Outcome ($Y$)", "einen normalverteilten Endpunkt ($Y$)", "einen normalverteilten Messwert ($Y$)") |> sample(1)
ort <- c("in der Uckermark", "im Oldenburger Land", "im Teuteburgerwald", "im Emsland", "im Wendland") |> sample(1)

exp <- lst(pflanze = c("ein Gewächshausexperiment",
                       "ein Freilandversuch",
                       "einen Versuch in einer Klimakammer",
                       "ein Feldexperiment"),
           tier = c("ein Stallexperiment", 
                    "ein Kreuzungsexperiment",
                    "einen Leistungssteigerungsversuch"))[[names(obser)]] %>% 
  sample(1)

x_val <- lst(pflanze = c("Düngestufen ($ctrl$ und $high$)",
                       "Lichtstufen ($none$ und $600lm$)",
                       "Lüftungssystemen und Folientunneln ($ctrl$ und $tornado$)",
                       "Substrattypen ($torf$ und $70p30n$)",
                       "Bewässerungstypen ($low$ und $high$)",
                       "Genotypen ($AA$ und $BB$)"),
           tier = c("Ernährungszusatz ($ctrl$ und $fedX$)", 
                    "Flüssignahrung ($ctrl$ und $flOw$)",
                    "Genotypen ($AA$ und $BB$)",
                    "Elterlinie ($Standard$ und $Xray$)",
                    "Lüftungssystem ($keins$ und $vorhanden$)",
                    "Bestandsdichte ($Verordnung$ und $Gesteigert$)"))[[names(obser)]] %>% 
  sample(1)

y_val <- lst(pflanze = c("Frischegewicht [kg/ha]",
                         "Trockengewicht [kg/ha]",
                         "Chlorophyllgehalt (SPAD-502Plus) [SPAD]",
                         "Proteingehalt [g/kg]"),
             tier = c("Schlachtgewicht [kg]", 
                      "Protein/Fettrate [\\%/kg]",
                      "Fettgehalt [\\%/kg]",
                      "Gewichtszuwachs in der 1LW"))[[names(obser)]] %>% 
  sample(1)


groups_vec <- x_val %>% 
  str_split("\\(|\\s|,|\\)", simplify = TRUE) %>% 
  str_subset("\\$") %>% 
  str_replace_all("\\$", "")
gen_data <- function(...){
  n_vec <- c(7:11) %>% sample(1)
  mean_vec <- c(25, 30, 35, 40, 45) %>% sample(1)
  sd_vec <- c(4, 6, 8, 10) %>% sample(1)
  temp_tbl <- tibble(temp = rnorm(n = n_vec, mean = mean_vec, sd = sd_vec)) %>%
    mutate(temp = round(temp, 1)) %>% 
    set_names(stringi::stri_rand_strings(1, 7, '[A-Z]')) %>% 
    gather
  return(temp_tbl)
}


effect_test <- c("die Teststatistik $T_{D}$", "der Effekt") |> sample(1)

type <- c("Student t-Tests", "Welch t-Tests") %>% sample(1)

hypo <- c("Formulieren Sie die wissenschaftliche Fragestellung!", 
          "Formulieren Sie das statistische Hypothesenpaar!") |> 
  sample(1)

sentence_name_vec <- sentence_func(name, pronom, attr_lst[[name]]) 

ques_vec <- c(str_c("Der t-Test. ", name, " erschaudert. ", sentence_name_vec$flaw, " Ein mächtiges Werkzeug ist der t-Test in den Händen desjenigen, der ", outcome_name, " hat. Aber erstmal überhaupt den t-Test rechnen können. Wie sah das Experiment von ", name, " überhaupt aus? ", sentence_name_vec$sweet_music, " ", name, " hat ", exp, " mit ", obser, " durchgeführt um eine neue technische Versuchsanlage zu testen. Bei dem Pilotexperiment mit sehr geringer Fallzahl $(n_1 = n_2 = 3)$ wurde die Behandlung ", x_val, " an den ", obser, " getestet und dabei wurde geschaut, ob der Versuch überhaupt technisch klappen könnte. Gemessen hat ", name, " dann als Messwert ", y_val, ". Warum der Versuch ", ort, " für ", project, " stattfinden musste, ist ", pronom[4], " bis heute ein Rätsel. Egal. Gibt es jetzt einen Zusammenhang zwischen der Behandlung und ", y_val, "?"),
              str_c(name, " ist ", ort, " für einen Pilotexperiment mit sehr geringer Fallzahl $(n_1 = n_2 = 3)$ mit ", obser, ". Allein diese Tatsache ist für ", pronom[5], " eine Erzählung wert. ", sentence_name_vec$flaw, "  Für ", project, " musste ", names(name), " ", exp, " mit ", obser, " durchführen und das sollte laut ", betreuer, " an diesem Ort besonders gut gelingen, da man hier gut neue technische Anlagen und Behandlungen fernab der Bevölkerung testen könne. Zeugen gibt es hier jedenfalls keine. Gar keine.  Alleine sein hilft jetzt aber nur bedingt, denn ", pronom[6], " Behandlung ", x_val, " und der Messwert ", y_val, " sollen mit einem t-Test ausgewertet werden. Immerhin weiß ", names(name), ", dass ", pronom[7], " Messwert einer Normalverteilung folgt. Hm..., was entspannendes wäre gut. ", sentence_name_vec$sport, ""),
              str_c("'Der t-Test testet ", outcome_name, ".', liest ", name, " laut. Das hilft jetzt auch nur bedingt weiter. ", sentence_name_vec$flaw, " Laut ", betreuer, " ist zwar ", pronom[4], " Messwert ", y_val, " normalverteilt, aber wie rechnet ", names(name), " jetzt einen t-Test? Für ", project, " zum Testen einer neuen technischen Anlage musste ", names(name), " ", exp, " mit ", obser, " ", ort, " durchführen. Als wäre das nicht schon anstrengend genug gewesen bei dem anspruchsvollen Pilotprojekt mit sehr geringer Fallzahl $(n_1 = n_2 = 3)$. Jetzt soll ", names(name), " auch noch testen, ob die Behandlung ", x_val, " ein signifikantes Ergebnis liefert. ", sentence_name_vec$sweet_film, "")) |> sample(1)


@ 

\paragraph{Berechnung des Student t-Test \underline{oder} Welch t-Test}

\Sexpr{ques_vec}

<<ttest-08, results='asis', echo = FALSE>>=
data_tbl <- rbind(tibble(ctrl = round(rnorm(n = 3,
                                         mean = sample(c(14, 17, 20), 1),
                                         sd = sample(c(3, 2), 1)), 1)) %>%
                  gather,
                  tibble(dose = round(rnorm(n = 3,
                                         mean = sample(c(16, 18, 22), 1),
                                         sd = sample(c(4, 5), 1)), 1)) %>%
                  gather) %>%
  set_names(c("treatment", "weight")) %>% 
  sample_n(size = nrow(.))

t_crit <- c(2.04, 1.96, 1.84, 1.64, 2.68) %>% sample(1)

kable(data_tbl, booktabs = TRUE, align = "c") %>% 
  kable_styling(latex_options = "hold_position")
@

Leider kennt sich \Sexpr{name} mit der Berechnung eines t-Tests überhaupt nicht aus. Deshalb braucht \Sexpr{names(name)} bei der Berechnung Ihre Hilfe!

\begin{enumerate}
  \item \Sexpr{hypo} \textbf{(1 Punkt)}
  \item Bestimmen Sie die Teststatistik $T_{D}$ eines \Sexpr{type}! \textbf{(3 Punkte)}
  \item Treffen Sie mit $T_{\alpha = 5\%} = \Sexpr{t_crit}$ eine Aussage zur Nullhypothese! Begründen Sie Ihre Antwort! \textbf{(2 Punkte)}
  \item Berechnen Sie den Effekt des \Sexpr{type}! \textbf{(1 Punkt)}
  \item Formulieren Sie eine Antwort an \Sexpr{name} über das Ergebnis Ihrer statistischen Analyse! \textbf{(2 Punkte)}
\end{enumerate}
