\section{Aufgabe \hfill (10 Punkte)}

\textit{Geben Sie grundsätzlich Formeln und Rechenweg zur Lösung der Teilaufgaben mit an!} \\[1Ex]
 
<<>>=
name <- par_lst$naming |> sample(1)
name_sec <- str_subset(par_lst$naming, name, negate = TRUE) |> sample(1)
avatar_file <- list.files(file.path(exam_path, "avatare"), full.names = TRUE) |> 
  str_subset(str_c(name, name_sec, sep = "|"))
jahr <- par_lst$year
obser <- par_lst$obser
avatar1file <- str_c("\\includegraphics[width = 1.3cm]{", avatar_file[1], "}")
avatar2file <- str_c("\\includegraphics[width = 1.3cm]{", avatar_file[2], "}")
@
 
%% --------------------------------------------------------------------
\begin{minipage}[t]{0.5\textwidth}
\Sexpr{avatar1file}\hspace{-4mm}\Sexpr{avatar2file}
\end{minipage}
\begin{minipage}[t]{0.5\textwidth}
\hfill
\href{https://youtu.be/kHmfEmU6lrk}{\includegraphics[width = 2cm]{img/youtube}}
\end{minipage}
\vspace{1ex}
%% --------------------------------------------------------------------

<<>>=

pronom <- lst(sie = c("ihrem", "ihrer", "ihren", "ihr", 
                      "sie", "ihre", "ihr", "die", "Frau"),
              er = c("seinem", "seiner", "seinen", "ihm", 
                     "ihn", "seine", "sein", "der", "Mann"))[[names(name)]]
project <- c(str_c("einer Abschlussarbeit"), str_c("einem Projektbericht"),
             str_c("einer Hausarbeit")) |> sample(1)
betreuer <- c(str_c("der Betreuerin"), str_c("des Betreuers")) |> sample(1)
outcome_name <- c("ein normalverteiltes Outcome ($Y$)", "einen normalverteilten Endpunkt ($Y$)", "einen normalverteilten Messwert ($Y$)") |> sample(1)
ort <- c("in der Uckermark", "im Oldenburger Land", "im Teuteburgerwald", "im Emsland", "im Wendland") |> sample(1)
ort_2 <- c("Die Uckermark", "Das Oldenburger Land", "Der Teuteburgerwald", "Das Emsland", "Das Wendland") |> sample(1)

exp <- lst(pflanze = c("einem Gewächshausexperiment",
                       "einem Freilandversuch",
                       "einem Versuch in einer Klimakammer",
                       "einem Feldexperiment"),
           tier = c("einem Stallexperiment", 
                    "einem Kreuzungsexperiment",
                    "einem Leistungssteigerungsversuch"))[[names(obser)]] %>% 
  sample(1)

x_val <- lst(pflanze = c("Düngung ($vorher$ und $nachher$)",
                         "Beschattung ($7d$ und $14d$)",
                         "Ausgeizen ($ctrl$ und $28d$)",
                         "Jäten ($Aussaat$ und $Ernte$)"),
           tier = c("Ernährungszusatz ($ohne$ und $14d$)", 
                    "Flüssignahrung ($1l/d$ und $5l/d$)",
                    "Genotypisierung ($0d$ und $14d$)",
                    "Bestandsdichte ($hoch$ und $niedrig$)"))[[names(obser)]] %>% 
  sample(1)

y_val <- lst(pflanze = c("Frischegewicht [kg/ha]",
                         "Trockengewicht [kg/ha]",
                         "Chlorophyllgehalt (SPAD-502Plus) [SPAD]",
                         "Proteingehalt [g/kg]"),
             tier = c("Schlachtgewicht [kg]", 
                      "Protein/Fettrate [\\%/kg]",
                      "Fettgehalt [\\%/kg]",
                      "Gewichtszuwachs in der 1LW"))[[names(obser)]] %>% 
  sample(1)

groups_vec <- x_val %>% 
  str_split("\\(|\\s|,|\\)", simplify = TRUE) %>% 
  str_subset("\\$") %>% 
  str_replace_all("\\$", "")
gen_data <- function(...){
  mean_vec <- c(25, 30, 35, 40, 45) %>% sample(1)
  sd_vec <- c(4, 6, 8, 10) %>% sample(1)
  temp_tbl <- tibble(temp = rnorm(n = 9, mean = mean_vec, sd = sd_vec)) %>%
    mutate(temp = round(temp, 1)) %>% 
    set_names(stringi::stri_rand_strings(1, 7, '[A-Z]')) %>% 
    gather |> 
    mutate(ID = 1:9)
  return(temp_tbl)
}

sentence_name_vec <- sentence_func(name, pronom, attr_lst[[name]])
attr_name_vec <- attr_lst[[name]]
attr_name_sec1_vec <- attr_lst[[name_sec[1]]]

ques_vec <- c(str_c("Alles voll mit ", obser, ". Aber das haben ", name, " und ", name_sec, " eben gemeinsam in ", project, " gemacht! Worum ging es aber konkret? Beide haben als ", outcome_name, " ", y_val, " von ", obser, " bestimmt. Die Daten haben beide zusammen in ", exp, " erhoben. In dem Experiment ging es um eine vorher/nachher Untersuchung an den gleichen ", obser, ". Als Behandlung wurde ", x_val, " eingesetzt. Nach der Meinung ", betreuer, " muss hier ein gepaarter t-Test gerechnet werden. Leider kennen sich beide nicht sehr gut in \\Rlogo aus."),
              str_c(name, " und ", name_sec, " haben sich dazu entschieden zusammenzuarbeiten. Das sollte alles etwas einfacher machen. Jeder hat zwar ein getrenntes Themenfeld aber den Hauptversuch machen beide gemeinsam. Das hat sich schonmal als gut Idee soweit herausgestellt. In ", project, " sollen beide herausfinden, ob es einen Zusammenhang zwischen ", x_val, " und ", y_val, " gibt. Die Besonderheit ist hierbei, dass die Messungen an der gleichen Beobachtung stattfinden. Beide messen also zweimal an den gleichen ", obser, ". Hier muss dann wohl auf ", outcome_name, " ein gepaarter t-Test gerechnet werden. Leider kennen sich beide nicht sehr gut in \\Rlogo aus."),
              str_c("Es gibt ja immer die Möglichkeit sich Hilfe zu holen. Das geht natürlich auch immer in ", project, ". Deshalb arbeiten ", name, " und ", name_sec, " gemeinsam an ", project, ". Das macht dann auch die Analyse ihres Hauptversuches einfacher. Zwar hat jeder von ihnen noch ein Subthema, aber auch da kann man sich ja helfen. In dem Hauptversuch wurde Folgendes von den beiden gemacht. ", name, " und ", name_sec, " haben sich ", obser, " angeschaut. Dabei geht um Zusammenhang zwischen ", x_val, " und ", y_val, ". Jetzt sollen beide einen gepaarten t-Test rechnen. Leider kennen sich beide nicht sehr gut in \\Rlogo aus.")) |> 
  sample(1)

@

\Sexpr{ques_vec}

<<ttest-R-04-a,  echo = FALSE>>=

data_tbl <- map_dfr(1:length(groups_vec), gen_data) %>% 
  set_names(c("treatment", "freshmatter", "ID")) %>% 
  select(ID, treatment, freshmatter) |> 
  mutate(treatment = factor(treatment, labels = groups_vec)) %>% 
  sample_n(size = nrow(.)) 

preprint <- t.test(filter(data_tbl, as.numeric(treatment) == 1)$freshmatter, 
                   filter(data_tbl, as.numeric(treatment) == 2)$freshmatter, paired = TRUE)
preprint$null.value <- "[condensed]"

x_val <- x_val |> str_split(" ", simplify = TRUE) |> magrittr::extract(1,1)
y_val <- y_val |> str_split(" ", simplify = TRUE) |> magrittr::extract(1,1)

preprint$data.name <- str_c(y_val, " by ", x_val)
preprint

@

Jetzt brauchen \Sexpr{name} und \Sexpr{name_sec} Ihre Hilfe bei der Berechnung eines gepaarten t-Tests in \Rlogo um ihre Arbeit dann in diesem Semester noch abschließen zu können.

\begin{enumerate}
  \item Formulieren Sie die wissenschaftliche Fragestellung! \textbf{(1 Punkt)}
  \item Formulieren Sie das statistische Hypothesenpaar! \textbf{(1 Punkt)}
\item Liegt ein signifikanter Unterschied zwischen den Gruppen vor?
  Begründen Sie Ihre Antwort! \textbf{(2 Punkte)}
\item Skizzieren Sie das sich ergebende 95\% Konfidenzintervall! \textbf{(2 Punkte)}
\item Interpretieren Sie den Effekt des gepaarten t-Tests! \textbf{(2 Punkte)}
\item Skizzieren Sie den sich ergebenden Boxplot der Differenzen! Welche Annahmen an die Daten haben Sie getroffen? Begründen Sie Ihre Antwort! \textbf{(2 Punkte)} 
\end{enumerate}

