\section{Aufgabe \hfill (8 Punkte)}

\textit{Geben Sie grundsätzlich Formeln und Rechenweg zur Lösung der Teilaufgaben mit an!} \\[1Ex]
 
<<>>=
name <- par_lst$naming |> sample(1)
name_sec <- str_subset(par_lst$naming, name, negate = TRUE) |> sample(1)
avatar_file <- list.files(file.path(exam_path, "avatare"), full.names = TRUE) |> 
  str_subset(str_c(name, name_sec, sep = "|"))
jahr <- par_lst$year
obser <- par_lst$obser
avatar1file <- str_c("\\includegraphics[width = 1.3cm]{", avatar_file[1], "}")
avatar2file <- str_c("\\includegraphics[width = 1.3cm]{", avatar_file[2], "}")
@
 
%% --------------------------------------------------------------------
\begin{minipage}[t]{0.5\textwidth}
\Sexpr{avatar1file}\hspace{-4mm}\Sexpr{avatar2file}
\end{minipage}
\begin{minipage}[t]{0.5\textwidth}
\hfill
\href{https://youtu.be/oMdtYbDInYE}{\includegraphics[width = 2cm]{img/youtube}}
\end{minipage}
\vspace{1ex}
%% --------------------------------------------------------------------

<<>>=

pronom <- lst(sie = c("ihrem", "ihrer", "ihren", "ihr", 
                      "sie", "ihre", "ihr", "die", "Frau"),
              er = c("seinem", "seiner", "seinen", "ihm", 
                     "ihn", "seine", "sein", "der", "Mann"))[[names(name)]]
project <- c(str_c("einer Abschlussarbeit"), str_c("einem Projektbericht"),
             str_c("einer Hausarbeit")) |> sample(1)
betreuer <- c(str_c("der Betreuerin"), str_c("des Betreuers")) |> sample(1)
outcome_name <- c("ein normalverteiltes Outcome ($Y$)", "einen normalverteilten Endpunkt ($Y$)", "einen normalverteilten Messwert ($Y$)") |> sample(1)
ort <- c("in der Uckermark", "im Oldenburger Land", "im Teuteburgerwald", "im Emsland", "im Wendland") |> sample(1)
ort_2 <- c("Die Uckermark", "Das Oldenburger Land", "Der Teuteburgerwald", "Das Emsland", "Das Wendland") |> sample(1)

exp <- lst(pflanze = c("einem Gewächshausexperiment",
                       "einem Freilandversuch",
                       "einem Versuch in einer Klimakammer",
                       "einem Feldexperiment"),
           tier = c("einem Stallexperiment", 
                    "einem Kreuzungsexperiment",
                    "einem Leistungssteigerungsversuch"))[[names(obser)]] %>% 
  sample(1)

x_val <- lst(pflanze = c("Düngung ($vorher$ und $nachher$)",
                         "Beschattung ($7d$ und $14d$)",
                         "Ausgeizen ($ctrl$ und $28d$)",
                         "Jäten ($Aussaat$ und $Ernte$)"),
           tier = c("Ernährungszusatz ($ohne$ und $14d$)", 
                    "Flüssignahrung ($1l/d$ und $5l/d$)",
                    "Genotypisierung ($0d$ und $14d$)",
                    "Bestandsdichte ($hoch$ und $niedrig$)"))[[names(obser)]] %>% 
  sample(1)

y_val <- lst(pflanze = c("Frischegewicht [kg/ha]",
                         "Trockengewicht [kg/ha]",
                         "Chlorophyllgehalt (SPAD-502Plus) [SPAD]",
                         "Proteingehalt [g/kg]"),
             tier = c("Schlachtgewicht [kg]", 
                      "Protein/Fettrate [\\%/kg]",
                      "Fettgehalt [\\%/kg]",
                      "Gewichtszuwachs in der 1LW"))[[names(obser)]] %>% 
  sample(1)

groups_vec <- x_val %>% 
  str_split("\\(|\\s|,|\\)", simplify = TRUE) %>% 
  str_subset("\\$") %>% 
  str_replace_all("\\$", "")
gen_data <- function(...){
  mean_vec <- c(25, 30, 35, 40, 45) %>% sample(1)
  sd_vec <- c(4, 6, 8, 10) %>% sample(1)
  temp_tbl <- tibble(temp = rnorm(n = 9, mean = mean_vec, sd = sd_vec)) %>%
    mutate(temp = round(temp, 1)) %>% 
    set_names(stringi::stri_rand_strings(1, 7, '[A-Z]')) %>% 
    gather |> 
    mutate(ID = 1:9)
  return(temp_tbl)
}

sentence_name_vec <- sentence_func(name, pronom, attr_lst[[name]])
attr_name_vec <- attr_lst[[name]]
attr_name_sec1_vec <- attr_lst[[name_sec[1]]]

ques_vec <- c(str_c("foo")) |> 
  sample(1)

@

\Sexpr{ques_vec}

Sie haben folgende Zahlenreihe $y$ vorliegen $y = \{\Sexpr{round(rnorm(n = sample(c(5,6,7), 1), mean = sample(c(15, 17, 19), 1), sd = sample(c(2, 3, 4), 1)))}\}$.

\begin{enumerate}
\item Visualisieren Sie den Mittelwert von $y$ in der untenstehenden Abbildung! \textbf{(4 Punkte)}
\item Beschriften Sie die $Y$ und $X$-Achse entsprechend! \textbf{(2 Punkte)}
\item Für die Berechnung der Varianz wird der Abstand der einzelnen Werte $y_i$ zum Mittelwert $\bar{y}$ quadriert. Warum muss der Abstand, $y_i - \bar{y}$, in der Varianzformel quadriert werden? Erklären Sie den Zusammenhang unter Berücksichtigung der Abbildung! \textbf{(2 Punkte)}  
\end{enumerate}

<<desc-01, results='asis', echo = FALSE, fig.height = 6, fig.width = 6, fig.align = "center", message = FALSE>>=
df <- data.frame()
ggplot(df) + geom_point() + xlim(0, 10) + ylim(0, 10) +
  xlab("") + ylab("") +
  theme_minimal() + theme(
  axis.text.x = element_blank(),
  axis.text.y = element_blank())
@